export type GuideLocale = "en" | "de" | "hu";
export type Step = { label: string; desc: string };
export type Note = { bold?: string; text: string };

export const coachContent = {
  en: {
    back: "← Back to app",
    cover: {
      eyebrow: "PowerFlow · User Guide",
      title: ["Coach", "Guide"],
      sub: "How to sign in as a coach, invite your athletes, and use the PowerFlow dashboard to track journal sentiment, training load, and assessment results.",
      signIn: "Sign in → app.power-flow.eu",
      meta: "Version 1.0 · April 2026 · app.power-flow.eu",
    },
    screens: {
      coachSignIn: "Sign-in — coach role",
      dashboard: "Coach dashboard",
      entriesTab: "Athlete — Recent entries tab",
      trainingTab: "Athlete — Training log tab",
      testsTab: "Athlete — Test results tab",
      dailyLog: "Daily log entry detail",
    },
    s01: {
      title: "Signing in as a coach",
      subtitle: "Google OAuth · Coach role",
      steps: [
        { label: "Open the app", desc: "Navigate to the PowerFlow URL. You will see the sign-in screen." },
        { label: "Select Coach role", desc: "Below the Google button, tap Coach. This sets your role permanently — coaches and athletes use separate accounts." },
        { label: "Sign in with Google", desc: "Complete the standard Google OAuth flow. You land directly on the Coach Dashboard — there is no setup wizard for coaches." },
        { label: "Your coach code is generated", desc: "A unique 8-character code is created automatically on first sign-in. You will see it at the top of the dashboard immediately." },
      ] as Step[],
      note: { bold: "Important:", text: " The Coach role is set permanently at first sign-in. If you need a separate athlete account, sign up with a different Google account." },
    },
    s02: {
      title: "Inviting your athletes",
      subtitle: "Coach code · Join link",
      intro: "Athletes connect to you using your unique coach code. There are two ways to share it:",
      steps: [
        { label: "Share your Coach Code directly", desc: "Your 8-character code is shown at the top of the dashboard (e.g. 3S1X4W23). Athletes enter it during onboarding (Step 6) or from the Coach section in their You tab." },
        { label: "Share your Join Link", desc: "The dashboard also shows a direct join link. Athletes who click it before signing in are automatically linked to you after they complete the Google sign-in — no code entry needed." },
        { label: "Athlete appears on your dashboard", desc: "Once linked, the athlete appears in your coach dashboard within seconds. No refresh needed." },
        { label: "Verify the link", desc: "The athlete card shows the athlete's name and their data starts populating as soon as they log entries. If they do not appear, ask them to check the Coach section in their You tab." },
      ] as Step[],
      note: { text: "Coach codes never expire. You can share the same code with all your athletes. If an athlete accidentally linked to the wrong coach, they can change their coach from the You tab." },
    },
    s03: {
      title: "Dashboard overview",
      subtitle: "Traffic-light system · Athlete cards",
      intro: "Each athlete appears as a card showing their 7-day snapshot. The header gives you the three numbers you need to triage at a glance.",
      steps: [
        { label: "Journal entry count", desc: "How many journal entries the athlete has written in the last 7 days. Zero entries is itself a signal — the athlete may be disengaged." },
        { label: "Positive sentiment rate", desc: "Percentage of entries in the last 7 days tagged as positive by AI. This is the core engagement metric." },
        { label: "Traffic-light flag", desc: "🟢 On-track: 55%+ positive. 🟡 Monitor: 30–55% positive — worth a check-in. 🔴 Attention: below 30% — this athlete needs direct contact." },
        { label: "Tap to expand", desc: "Tap any athlete card to open their full profile with three tabs: Recent Entries, Training Log, and Test Results." },
      ] as Step[],
      note: { bold: "The 🔴 Attention flag is the most important signal.", text: " Check these athletes first in every session review. A drop from 🟢 to 🔴 in one week often correlates with an upcoming competition or a bad training block." },
    },
    s04: {
      title: "Recent entries tab",
      subtitle: "Journal sentiment · AI theme detection",
      steps: [
        { label: "Open an athlete card", desc: "Tap the athlete card on the dashboard. The default tab is Recent Entries." },
        { label: "Read sentiment at a glance", desc: "Each entry has a colour dot: 🟢 positive, ⚪ neutral, 🔴 negative. The context tag (Pre-comp, Post-comp, General, etc.) is shown next to the date." },
        { label: "Read the full entry", desc: "Tap any entry card to read the full text. The AI-detected themes appear as chips below the text (confidence, anxiety, focus, pressure, recovery, etc.)." },
        { label: "Spot patterns", desc: "Look for clusters of negative entries around specific contexts. Repeated 'competition anxiety' or 'confidence' themes across multiple entries signal a clear coaching focus area." },
        { label: "Scroll back in time", desc: "The tab shows the last 50 entries, newest first. Scroll to see older entries and track trends over multiple weeks." },
      ] as Step[],
      note: { text: "Sentiment is tagged automatically by AI, but it is not infallible. A negative entry does not always mean the athlete is struggling — read the actual text. Use sentiment as a filter to prioritise which entries to read, not as the final verdict." },
    },
    s05: {
      title: "Training log tab",
      subtitle: "Mood sparkline · Daily log entries",
      steps: [
        { label: "Open Training Log tab", desc: "Inside an athlete card, tap the Training tab. You see the current Mon–Sun training week." },
        { label: "Read the sparkline", desc: "Each day shows a bar filled to the athlete's mood rating (1–10). 🏋️ = training day, 💤 = rest day, — = no check-in logged." },
        { label: "Week summary", desc: "The header shows total training days logged and the weekly average mood. A low average across training days is more concerning than a single bad day." },
        { label: "Read daily log entries", desc: "Below the sparkline, the two most recent days are expanded with their full answers: thoughts before the session, how it went, what went well, frustrations, and next-session focus." },
        { label: "Missing check-ins", desc: "Days with no entry (—) mean the athlete did not log. If multiple consecutive days are missing, it may indicate avoidance or disengagement — worth a message." },
      ] as Step[],
      note: { text: "Cross-reference the training log with journal entries. A mood of 8/10 on a training day paired with a negative journal entry from the same day often means the athlete is performing well physically but struggling mentally — a nuanced coaching moment." },
    },
    s06: {
      title: "Test results tab",
      subtitle: "SAT · ACSI · CSAI-2 · DAS",
      intro: "Once an athlete completes and unlocks a test, the scored results appear here automatically. No action needed from you.",
      steps: [
        { label: "SAT — Sport Anxiety Test", desc: "Total score out of 100. Lower is better. Cross-reference spikes with upcoming competition dates." },
        { label: "ACSI — Coping Skills Inventory", desc: "Four sub-scores: coping with adversity, concentration, confidence, and goal-setting. Each expressed as a percentage. Look for the lowest score — that is often the first coaching focus." },
        { label: "CSAI-2 — Competitive State Anxiety", desc: "Three scores: cognitive anxiety (worry), somatic anxiety (body symptoms), and self-confidence. High cognitive + low confidence = classic pre-competition anxiety pattern." },
        { label: "DAS — Depression, Anxiety, Stress", desc: "Screens for depression-prone thinking, anxiety, and stress. A high DAS alongside many negative journal entries warrants a direct conversation and possible referral." },
      ] as Step[],
      note: { text: "Tests require a one-time athlete payment to unlock results. If results are not showing, the athlete may not have completed the unlock payment. You cannot see partial or unpaid results." },
    },
    s07: {
      title: "Check-ins tab",
      subtitle: "Weekly & monthly athlete self-ratings",
      steps: [
        { label: "Access check-ins", desc: "Expand any athlete card and tap the Check-ins tab. You'll see their weekly and monthly submissions, most recent first." },
        { label: "What each entry shows", desc: "Five self-ratings (1–10): overall mood, training quality, energy levels, sleep quality, and readiness for next week or month. These give you a structured numerical picture alongside the journal narrative." },
        { label: "Written reflections", desc: "Below the ratings: the athlete's biggest win or positive moment, main challenge, and their stated focus for the following week or month. Read these before check-in calls — they often surface what the athlete is most focused on." },
        { label: "Monthly check-ins", desc: "Monthly submissions include three additional questions: biggest breakthrough, key lesson learned about themselves, and their intention for the next month. These are the closest thing to a structured session summary the athlete produces independently." },
      ] as Step[],
      note: { text: "Check-in data cannot be edited by the coach — they are submitted by the athlete as-is. Cross-reference with journal entries from the same week for the fullest picture." },
    },
    s08: {
      title: "Assigning psychological tests",
      subtitle: "SAT · ACSI · CSAI-2 · DAS",
      steps: [
        { label: "Assign a test", desc: "Expand an athlete card → Profile tab → scroll to Assign a test. Select SAT, ACSI, CSAI-2, or DAS and tap Assign. The test appears as a prompt in the athlete's Tools tab immediately." },
        { label: "Athlete completes it", desc: "The athlete sees the assigned test highlighted in their Tools tab. Once they complete and unlock the results, the assignment is cleared automatically." },
        { label: "View results", desc: "Completed results appear in your Test Scores tab for that athlete. You can cross-reference scores with journal sentiment — low ACSI concentration alongside negative entries near competition is a strong early warning pattern." },
        { label: "When to assign", desc: "Use test assignment to get a structured psychological baseline at the start of coaching. Re-assign when journal patterns suggest a specific area (anxiety, confidence, depression risk) needs formal measurement." },
      ] as Step[],
    },
    s09: {
      title: "Ego States — coach view",
      subtitle: "Athlete's psychological personas · Profile tab",
      steps: [
        { label: "Where to find them", desc: "Expand an athlete card → Profile tab → scroll to the bottom. If the athlete has mapped ego states through Coach AI, each saved state appears with its name, domain, and activation ritual." },
        { label: "How athletes map them", desc: "Athletes ask Coach AI to run an ego state mapping session. The AI walks through eight questions (name, colour, posture, body feeling, inner voice, origin, domain, shadow side, activation ritual) and the athlete saves the resulting state card." },
        { label: "Using them in sessions", desc: "Refer to the athlete's states by name in your check-in calls: 'Which state were you in during that heavy squat session?' Use the shadow side field to identify when a state is bleeding into the wrong context. Use the activation ritual to guide pre-competition preparation." },
        { label: "State conflicts", desc: "The most common performance issue is the wrong state for the moment — Analyst-mode during execution, Warrior-mode during recovery. When you spot this pattern in journal language ('I kept second-guessing', 'couldn't switch off'), it's an ego state conflict worth naming directly." },
      ] as Step[],
    },
    s10: {
      title: "Quick reference",
      subtitle: "Dashboard signals at a glance",
      tableHeaders: ["Signal", "What it means", "Suggested action"] as [string, string, string],
      tableRows: [
        ["🟢 On-track (55%+ positive)", "Athlete is expressing positive mindset consistently", "Review entries, reinforce what's working"],
        ["🟡 Monitor (30–55% positive)", "Mixed sentiment — could be a rough week or a trend", "Read entries, check training log mood, send a message"],
        ["🔴 Attention (<30% positive)", "Predominantly negative entries — athlete is struggling", "Contact the athlete directly before next session"],
        ["0 entries this week", "No journal activity", "Remind athlete to log — engagement is the first step"],
        ["Mood drop (e.g. 8 → 4/10)", "Sudden mood decline in training log", "Check journal entries from the same days for context"],
        ["Low ACSI Confidence <50%", "Self-confidence deficit in competition context", "Focus next session on confidence-building exercises"],
        ["High CSAI-2 Cognitive Anxiety", "Athlete is worrying about performance outcomes", "Introduce thought-stopping or re-framing techniques"],
        ["Check-in ratings drop", "Athlete's 5 self-ratings decline week-on-week", "Read written reflections from same week — often explains the drop"],
        ["Test assigned (pending)", "Athlete has an assigned test not yet completed", "Follow up — completion gives you a structured baseline for the area you flagged"],
      ] as [string, string, string][],
      note: { bold: "Weekly review rhythm (suggested):", text: " Check all athlete flags once a week before your group or individual sessions. Read full entries for any 🔴 athletes first. Scan training log mood trends for all athletes. Note any test results that appeared since last review." },
    },
  },

  de: {
    back: "← Zurück zur App",
    cover: {
      eyebrow: "PowerFlow · Benutzerhandbuch",
      title: ["Coach", "Leitfaden"],
      sub: "So meldest du dich als Coach an, lädst deine Athleten ein und nutzt das PowerFlow-Dashboard, um Journal-Sentiment, Trainingsbelastung und Testergebnisse zu verfolgen.",
      signIn: "Anmelden → app.power-flow.eu",
      meta: "Version 1.0 · April 2026 · app.power-flow.eu",
    },
    screens: {
      coachSignIn: "Anmelden — Coach-Rolle",
      dashboard: "Coach-Dashboard",
      entriesTab: "Athlet — Tab Letzte Einträge",
      trainingTab: "Athlet — Tab Trainingsprotokoll",
      testsTab: "Athlet — Tab Testergebnisse",
      dailyLog: "Tagesprotokoll-Detail",
    },
    s01: {
      title: "Als Coach anmelden",
      subtitle: "Google OAuth · Coach-Rolle",
      steps: [
        { label: "App öffnen", desc: "Navigiere zur PowerFlow-URL. Du siehst den Anmeldebildschirm." },
        { label: "Coach-Rolle auswählen", desc: "Unter dem Google-Button tippst du auf Coach. Das setzt deine Rolle dauerhaft – Coaches und Athleten nutzen getrennte Konten." },
        { label: "Mit Google anmelden", desc: "Schließe den Google-OAuth-Prozess ab. Du landest direkt im Coach-Dashboard – es gibt keinen Einrichtungsassistenten für Coaches." },
        { label: "Dein Coach-Code wird erstellt", desc: "Ein einzigartiger 8-stelliger Code wird automatisch beim ersten Anmelden erstellt. Du siehst ihn sofort oben im Dashboard." },
      ] as Step[],
      note: { bold: "Wichtig:", text: " Die Coach-Rolle wird beim ersten Anmelden dauerhaft vergeben. Falls du ein separates Athleten-Konto benötigst, melde dich mit einem anderen Google-Konto an." },
    },
    s02: {
      title: "Athleten einladen",
      subtitle: "Coach-Code · Einladungslink",
      intro: "Athleten verbinden sich mit dir über deinen einzigartigen Coach-Code. Es gibt zwei Möglichkeiten, ihn zu teilen:",
      steps: [
        { label: "Coach-Code direkt teilen", desc: "Dein 8-stelliger Code wird oben im Dashboard angezeigt (z.B. 3S1X4W23). Athleten geben ihn beim Onboarding (Schritt 6) oder über den Coach-Bereich in ihrem Ich-Tab ein." },
        { label: "Einladungslink teilen", desc: "Das Dashboard zeigt auch einen direkten Einladungslink. Athleten, die ihn vor dem Anmelden anklicken, werden automatisch mit dir verknüpft – keine Code-Eingabe nötig." },
        { label: "Athlet erscheint im Dashboard", desc: "Nach der Verknüpfung erscheint der Athlet innerhalb von Sekunden in deinem Coach-Dashboard. Kein Aktualisieren nötig." },
        { label: "Verbindung verifizieren", desc: "Die Athleten-Karte zeigt den Namen und die Daten beginnen zu erscheinen, sobald Einträge geloggt werden. Falls der Athlet nicht erscheint, bitte ihn, den Coach-Bereich in seinem Ich-Tab zu prüfen." },
      ] as Step[],
      note: { text: "Coach-Codes laufen nie ab. Du kannst denselben Code mit allen deinen Athleten teilen. Falls ein Athlet den falschen Coach verknüpft hat, kann er seinen Coach über den Ich-Tab wechseln." },
    },
    s03: {
      title: "Dashboard-Übersicht",
      subtitle: "Ampel-System · Athleten-Karten",
      intro: "Jeder Athlet erscheint als Karte mit einem 7-Tage-Schnappschuss. Die Kopfzeile zeigt dir die drei Zahlen, die du auf einen Blick brauchst.",
      steps: [
        { label: "Journaleintrags-Anzahl", desc: "Wie viele Journaleinträge der Athlet in den letzten 7 Tagen geschrieben hat. Null Einträge ist selbst ein Signal – der Athlet könnte desengagiert sein." },
        { label: "Positiv-Sentiment-Rate", desc: "Prozentsatz der Einträge in den letzten 7 Tagen, die von der KI als positiv getaggt wurden. Dies ist die zentrale Engagement-Kennzahl." },
        { label: "Ampel-Flag", desc: "🟢 Auf Kurs: 55%+ positiv. 🟡 Beobachten: 30–55% positiv – ein Check-in ist empfehlenswert. 🔴 Achtung: unter 30% – dieser Athlet braucht direkten Kontakt." },
        { label: "Zum Erweitern tippen", desc: "Tippe auf eine Athleten-Karte, um das vollständige Profil mit drei Tabs zu öffnen: Letzte Einträge, Trainingsprotokoll und Testergebnisse." },
      ] as Step[],
      note: { bold: "Das 🔴 Achtung-Flag ist das wichtigste Signal.", text: " Prüfe diese Athleten bei jeder Überprüfung zuerst. Ein Abfall von 🟢 auf 🔴 innerhalb einer Woche korreliert oft mit einem bevorstehenden Wettkampf oder einem schlechten Trainingsblock." },
    },
    s04: {
      title: "Tab Letzte Einträge",
      subtitle: "Journal-Sentiment · KI-Themenerkennung",
      steps: [
        { label: "Athleten-Karte öffnen", desc: "Tippe auf die Athleten-Karte im Dashboard. Der Standard-Tab ist Letzte Einträge." },
        { label: "Sentiment auf einen Blick lesen", desc: "Jeder Eintrag hat einen Farbpunkt: 🟢 positiv, ⚪ neutral, 🔴 negativ. Der Kontext-Tag (Vor Wettkampf, Nach Wettkampf, Allgemein, etc.) wird neben dem Datum angezeigt." },
        { label: "Vollständigen Eintrag lesen", desc: "Tippe auf eine Eintrags-Karte, um den vollständigen Text zu lesen. Die KI-erkannten Themen erscheinen als Chips unter dem Text (Selbstvertrauen, Angst, Fokus, Druck, Erholung, etc.)." },
        { label: "Muster erkennen", desc: "Achte auf Cluster negativer Einträge in bestimmten Kontexten. Wiederkehrende Themen 'Wettkampfangst' oder 'Selbstvertrauen' über mehrere Einträge signalisieren einen klaren Coaching-Fokusbereich." },
        { label: "Weiter zurück scrollen", desc: "Der Tab zeigt die letzten 50 Einträge, neueste zuerst. Scrolle, um ältere Einträge zu sehen und Trends zu verfolgen." },
      ] as Step[],
      note: { text: "Das Sentiment wird automatisch von der KI getaggt, ist aber nicht unfehlbar. Ein negativer Eintrag bedeutet nicht immer, dass der Athlet kämpft – lies den tatsächlichen Text. Nutze das Sentiment als Filter, nicht als endgültiges Urteil." },
    },
    s05: {
      title: "Tab Trainingsprotokoll",
      subtitle: "Stimmungs-Sparkline · Tägliche Protokolleinträge",
      steps: [
        { label: "Tab Trainingsprotokoll öffnen", desc: "Innerhalb einer Athleten-Karte tippst du auf Training. Du siehst die aktuelle Mo–So Trainingswoche." },
        { label: "Sparkline lesen", desc: "Jeder Tag zeigt einen Balken, der auf die Stimmungsbewertung des Athleten (1–10) gefüllt ist. 🏋️ = Trainingstag, 💤 = Ruhetag, — = kein Check-in geloggt." },
        { label: "Wochenzusammenfassung", desc: "Die Kopfzeile zeigt die Gesamtzahl der geloggten Trainingstage und die durchschnittliche Wochenstimmung. Ein niedriger Durchschnitt über Trainingstage ist besorgniserregender als ein einzelner schlechter Tag." },
        { label: "Tägliche Protokolleinträge lesen", desc: "Unter der Sparkline sind die zwei letzten Tage mit ihren vollständigen Antworten erweitert: Gedanken vor der Einheit, wie es lief, was gut war, Frustration und Fokus für die nächste Einheit." },
        { label: "Fehlende Check-ins", desc: "Tage ohne Eintrag (—) bedeuten, dass der Athlet nichts geloggt hat. Mehrere aufeinanderfolgende fehlende Tage können auf Vermeidung oder Desengagement hinweisen – wert eine Nachricht." },
      ] as Step[],
      note: { text: "Verknüpfe das Trainingsprotokoll mit Journaleinträgen. Eine Stimmung von 8/10 an einem Trainingstag kombiniert mit einem negativen Journaleintrag vom selben Tag bedeutet oft, dass der Athlet körperlich gut performt, aber mental kämpft – ein nuancierter Coaching-Moment." },
    },
    s06: {
      title: "Tab Testergebnisse",
      subtitle: "SAT · ACSI · CSAI-2 · DAS",
      intro: "Sobald ein Athlet einen Test abschließt und freischaltet, erscheinen die Bewertungsergebnisse hier automatisch. Von dir ist keine Aktion erforderlich.",
      steps: [
        { label: "SAT – Sport Anxiety Test", desc: "Gesamtpunktzahl von 100. Niedriger ist besser. Verknüpfe Spitzen mit bevorstehenden Wettkampfterminen." },
        { label: "ACSI – Coping Skills Inventory", desc: "Vier Teilwerte: Umgang mit Rückschlägen, Konzentration, Selbstvertrauen und Zielsetzung. Jeweils als Prozentsatz. Achte auf den niedrigsten Wert – das ist oft der erste Coaching-Fokus." },
        { label: "CSAI-2 – Competitive State Anxiety", desc: "Drei Werte: kognitive Angst (Sorgen), somatische Angst (Körpersymptome) und Selbstvertrauen. Hohe kognitive Angst + niedriges Selbstvertrauen = klassisches Vorab-Wettkampf-Angstmuster." },
        { label: "DAS – Depression, Anxiety, Stress", desc: "Screent auf depressives Denken, Angst und Stress. Ein hoher DAS-Wert zusammen mit vielen negativen Journaleinträgen erfordert ein direktes Gespräch und möglicherweise eine Überweisung." },
      ] as Step[],
      note: { text: "Tests erfordern eine einmalige Athletenzahlung, um Ergebnisse freizuschalten. Falls keine Ergebnisse angezeigt werden, hat der Athlet möglicherweise die Freischaltungszahlung nicht abgeschlossen. Du kannst keine unbezahlten Ergebnisse sehen." },
    },
    s07: {
      title: "Tab Check-ins",
      subtitle: "Wöchentliche und monatliche Athleten-Selbstbewertungen",
      steps: [
        { label: "Check-ins öffnen", desc: "Erweitere eine Athleten-Karte und tippe auf den Tab Check-ins. Du siehst ihre wöchentlichen und monatlichen Einreichungen, neueste zuerst." },
        { label: "Was jeder Eintrag zeigt", desc: "Fünf Selbstbewertungen (1–10): Gesamtstimmung, Trainingsqualität, Energielevel, Schlafqualität und Bereitschaft für die nächste Woche oder den nächsten Monat." },
        { label: "Schriftliche Reflexionen", desc: "Unter den Bewertungen: der größte Erfolg des Athleten, die Hauptherausforderung und sein erklärter Fokus für die folgende Woche oder den folgenden Monat. Lies das vor Check-in-Gesprächen – oft zeigt es, worauf der Athlet am meisten fokussiert ist." },
        { label: "Monatliche Check-ins", desc: "Monatliche Einreichungen umfassen drei zusätzliche Fragen: größter Durchbruch, wichtigste Selbsterkenntnis und Intention für den nächsten Monat." },
      ] as Step[],
      note: { text: "Check-in-Daten können vom Coach nicht bearbeitet werden – sie werden vom Athleten unverändert eingereicht. Verknüpfe mit Journaleinträgen aus derselben Woche für das vollständigste Bild." },
    },
    s08: {
      title: "Psychologische Tests zuweisen",
      subtitle: "SAT · ACSI · CSAI-2 · DAS",
      steps: [
        { label: "Test zuweisen", desc: "Athleten-Karte erweitern → Profil-Tab → nach Testzuweisung scrollen. SAT, ACSI, CSAI-2 oder DAS auswählen und Zuweisen tippen. Der Test erscheint sofort als Aufforderung im Tools-Tab des Athleten." },
        { label: "Athlet schließt ihn ab", desc: "Der Athlet sieht den zugewiesenen Test hervorgehoben in seinem Tools-Tab. Nach Abschluss und Freischaltung wird die Zuweisung automatisch gelöscht." },
        { label: "Ergebnisse ansehen", desc: "Abgeschlossene Ergebnisse erscheinen in deinem Testergebnis-Tab für diesen Athleten. Du kannst Werte mit Journal-Sentiment vergleichen – niedriger ACSI-Konzentrationswert neben negativen Einträgen vor Wettkämpfen ist ein starkes Frühwarnsignal." },
        { label: "Wann zuweisen", desc: "Nutze die Testzuweisung, um eine strukturierte psychologische Ausgangsbasis zu Beginn des Coachings zu erhalten. Weise erneut zu, wenn Journal-Muster darauf hinweisen, dass ein bestimmter Bereich formale Messung benötigt." },
      ] as Step[],
    },
    s09: {
      title: "Ego-States – Coach-Ansicht",
      subtitle: "Psychologische Personas des Athleten · Profil-Tab",
      steps: [
        { label: "Wo sie zu finden sind", desc: "Athleten-Karte erweitern → Profil-Tab → nach unten scrollen. Falls der Athlet Ego-States über Coach AI gemappt hat, erscheint jeder gespeicherte State mit Name, Domäne und Aktivierungsritual." },
        { label: "Wie Athleten sie mappen", desc: "Athleten bitten Coach AI, eine Ego-State-Mapping-Sitzung durchzuführen. Die KI stellt acht Fragen (Name, Farbe, Haltung, Körpergefühl, innere Stimme, Ursprung, Domäne, Schattenseite, Aktivierungsritual) und der Athlet speichert die resultierende State-Karte." },
        { label: "In Sitzungen nutzen", desc: "Beziehe dich bei Check-in-Gesprächen auf die States des Athleten beim Namen. Nutze das Schattenseite-Feld, um zu identifizieren, wenn ein State in den falschen Kontext übergeht. Nutze das Aktivierungsritual zur Wettkampfvorbereitung." },
        { label: "State-Konflikte", desc: "Die häufigste Leistungsproblematik ist der falsche State im falschen Moment – Analyse-Modus bei der Ausführung, Krieger-Modus bei der Erholung. Wenn du dieses Muster in Journalsprache erkennst, ist ein Ego-State-Konflikt es wert, direkt benannt zu werden." },
      ] as Step[],
    },
    s10: {
      title: "Kurzreferenz",
      subtitle: "Dashboard-Signale auf einen Blick",
      tableHeaders: ["Signal", "Bedeutung", "Empfohlene Aktion"] as [string, string, string],
      tableRows: [
        ["🟢 Auf Kurs (55%+ positiv)", "Athlet drückt durchgehend positive Mentalität aus", "Einträge überprüfen, Funktionierendes bestärken"],
        ["🟡 Beobachten (30–55% positiv)", "Gemischtes Sentiment – könnte eine schwierige Woche oder ein Trend sein", "Einträge lesen, Trainingsprotokoll-Stimmung prüfen, Nachricht senden"],
        ["🔴 Achtung (<30% positiv)", "Überwiegend negative Einträge – Athlet kämpft", "Athleten direkt kontaktieren vor der nächsten Einheit"],
        ["0 Einträge diese Woche", "Keine Journal-Aktivität", "Athleten erinnern zu loggen – Engagement ist der erste Schritt"],
        ["Stimmungsabfall (z.B. 8 → 4/10)", "Plötzlicher Stimmungsrückgang im Trainingsprotokoll", "Journaleinträge vom selben Tag nach Kontext prüfen"],
        ["Niedriger ACSI-Selbstvertrauen <50%", "Selbstvertrauen-Defizit im Wettkampfkontext", "Nächste Einheit auf selbstvertrauensbildende Übungen fokussieren"],
        ["Hohe CSAI-2 kognitive Angst", "Athlet sorgt sich um Leistungsergebnisse", "Gedankenstopp oder Umformulierungstechniken einführen"],
        ["Check-in-Bewertungen sinken", "5 Selbstbewertungen des Athleten sinken Woche für Woche", "Schriftliche Reflexionen aus derselben Woche lesen"],
        ["Test zugewiesen (ausstehend)", "Athlet hat einen zugewiesenen Test noch nicht abgeschlossen", "Nachfassen – Abschluss gibt dir eine strukturierte Ausgangsbasis"],
      ] as [string, string, string][],
      note: { bold: "Wöchentlicher Überprüfungsrhythmus (Vorschlag):", text: " Prüfe alle Athleten-Flags einmal pro Woche vor deinen Sitzungen. Lies zuerst alle Einträge für 🔴 Athleten. Scanne Trainingsprotokoll-Stimmungstrends für alle Athleten. Notiere alle Testergebnisse, die seit der letzten Überprüfung erschienen sind." },
    },
  },

  hu: {
    back: "← Vissza az appba",
    cover: {
      eyebrow: "PowerFlow · Felhasználói kézikönyv",
      title: ["Edző", "Kézikönyv"],
      sub: "Hogyan jelentkezz be edzőként, hívj meg atlétákat, és használd a PowerFlow irányítópultját a napló-hangulat, edzésterhelés és felmérési eredmények nyomon követéséhez.",
      signIn: "Bejelentkezés → app.power-flow.eu",
      meta: "1.0 verzió · 2026. április · app.power-flow.eu",
    },
    screens: {
      coachSignIn: "Bejelentkezés — edző szerepkör",
      dashboard: "Edző irányítópult",
      entriesTab: "Atléta — Legutóbbi bejegyzések fül",
      trainingTab: "Atléta — Edzésnapló fül",
      testsTab: "Atléta — Teszteredmények fül",
      dailyLog: "Napi naplóbejegyzés részlet",
    },
    s01: {
      title: "Bejelentkezés edzőként",
      subtitle: "Google OAuth · Edző szerepkör",
      steps: [
        { label: "Nyisd meg az appot", desc: "Navigálj a PowerFlow URL-re. A bejelentkezési képernyőt fogod látni." },
        { label: "Válaszd az Edző szerepkört", desc: "A Google gomb alatt érintsd meg az Edző lehetőséget. Ez véglegesre állítja a szerepkörödet – edzők és atlétók külön fiókokat használnak." },
        { label: "Bejelentkezés Google-lal", desc: "Hajtsd végre a szokásos Google OAuth folyamatot. Egyenesen az Edző irányítópultra kerülsz – edzők számára nincs beállítási varázsló." },
        { label: "Létrejön az edző kódod", desc: "Az első bejelentkezéskor automatikusan létrejön egy egyedi 8 karakteres kód. Azonnal látni fogod az irányítópult tetején." },
      ] as Step[],
      note: { bold: "Fontos:", text: " Az Edző szerepkör végleges az első bejelentkezéstől. Ha külön atléta fiókra van szükséged, egy másik Google-fiókkal regisztrálj." },
    },
    s02: {
      title: "Atlétáid meghívása",
      subtitle: "Edző kód · Csatlakozási link",
      intro: "Az atlétok az egyedi edző kódoddal kapcsolódnak hozzád. Kétféleképpen oszthatod meg:",
      steps: [
        { label: "Edző kód közvetlen megosztása", desc: "A 8 karakteres kódod az irányítópult tetején látható (pl. 3S1X4W23). Az atlétok a beléptetési folyamatban (6. lépés) vagy az Én fülük Edző részéből adják meg." },
        { label: "Csatlakozási link megosztása", desc: "Az irányítópult közvetlen csatlakozási linket is mutat. Azok az atlétok, akik a bejelentkezés előtt kattintanak rá, automatikusan hozzád kapcsolódnak – nem kell kódot beírniuk." },
        { label: "Az atléta megjelenik az irányítópulton", desc: "A kapcsolódás után az atléta másodperceken belül megjelenik az edző irányítópultján. Nem kell frissíteni." },
        { label: "A kapcsolat ellenőrzése", desc: "Az atléta kártyán megjelenik a neve, és az adatok elkezdnek feltöltődni, amint bejegyzéseket naplóznak. Ha nem jelenik meg, kérd meg az atlétát, ellenőrizze az Edző részt az Én fülén." },
      ] as Step[],
      note: { text: "Az edző kódok soha nem járnak le. Ugyanazt a kódot megoszthatod az összes atlétáddal. Ha egy atléta véletlenül rossz edzőhöz kapcsolódott, az Én fülről változtathat edzőt." },
    },
    s03: {
      title: "Irányítópult áttekintése",
      subtitle: "Jelzőlámpa rendszer · Atléta kártyák",
      intro: "Minden atléta kártyaként jelenik meg a 7 napos pillanatképpel. A fejléc mutatja azt a három számot, amelyre egy pillantásra szükséged van.",
      steps: [
        { label: "Naplóbejegyzések száma", desc: "Hány naplóbejegyzést írt az atléta az elmúlt 7 napban. A nulla bejegyzés önmagában is jelzés – az atléta esetleg nem elkötelezett." },
        { label: "Pozitív hangulat aránya", desc: "Az elmúlt 7 napban az AI által pozitívnak jelölt bejegyzések százaléka. Ez az alapvető elköteleződési mutató." },
        { label: "Jelzőlámpa jelzés", desc: "🟢 Pályán: 55%+ pozitív. 🟡 Figyelés: 30–55% pozitív – érdemes bejelentkezni. 🔴 Figyelem: 30% alatt – ez az atléta közvetlen kapcsolatot igényel." },
        { label: "Érintsd meg a kibontáshoz", desc: "Érintsd meg az atléta kártyát a teljes profil megnyitásához három füllel: Legutóbbi bejegyzések, Edzésnapló és Teszteredmények." },
      ] as Step[],
      note: { bold: "A 🔴 Figyelem jelzés a legfontosabb.", text: " Minden felülvizsgálati munkamenetnél először ezeket az atlétákat ellenőrizd. A 🟢-ről 🔴-re való esés egy héten belül gyakran kapcsolódik közelgő versenyhez vagy rossz edzésblokhoz." },
    },
    s04: {
      title: "Legutóbbi bejegyzések fül",
      subtitle: "Napló-hangulat · AI-témák felismerése",
      steps: [
        { label: "Nyisd meg az atléta kártyát", desc: "Érintsd meg az atléta kártyát az irányítópulton. Az alapértelmezett fül a Legutóbbi bejegyzések." },
        { label: "Hangulat olvasása egy pillantásra", desc: "Minden bejegyzésnek van egy színes pontja: 🟢 pozitív, ⚪ semleges, 🔴 negatív. A kontextus-cimke (Verseny előtt, Verseny után, Általános stb.) a dátum mellett jelenik meg." },
        { label: "A teljes bejegyzés olvasása", desc: "Érintsd meg a bejegyzés kártyát a teljes szöveg olvasásához. Az AI által felismert témák chipsként jelennek meg a szöveg alatt (önbizalom, szorongás, fókusz, nyomás, regenerálódás stb.)." },
        { label: "Minták észlelése", desc: "Keress csoportokat negatív bejegyzésekből adott kontextusokban. Ismétlődő 'verseny szorongás' vagy 'önbizalom' témák több bejegyzésben egyértelmű coaching fókuszterületet jeleznek." },
        { label: "Visszagörgetés időben", desc: "A fül az utolsó 50 bejegyzést mutatja, legújabbak előre. Görgess régebbi bejegyzések megtekintéséhez és több hetes trendek nyomon követéséhez." },
      ] as Step[],
      note: { text: "A hangulatot automatikusan jelöli meg az AI, de nem tévedhetetlen. A negatív bejegyzés nem mindig jelent nehézséget – olvasd el a tényleges szöveget. A hangulatot szűrőként használd a prioritizáláshoz, nem végső ítéletként." },
    },
    s05: {
      title: "Edzésnapló fül",
      subtitle: "Hangulat-sparkline · Napi naplóbejegyzések",
      steps: [
        { label: "Nyisd meg az Edzésnapló fület", desc: "Az atléta kártyán belül érintsd meg az Edzés fület. Az aktuális H–V edzéshetet látod." },
        { label: "A sparkline olvasása", desc: "Minden nap megmutat egy sávot, amely az atléta hangulat értékelésére van töltve (1–10). 🏋️ = edzésnap, 💤 = pihenőnap, — = nem naplózott bejelentkezés." },
        { label: "Heti összefoglalás", desc: "A fejléc mutatja a naplózott edzésnapok összesítését és a heti átlag hangulatot. Az alacsony átlag az edzésnapokon aggodalmasabb, mint egyetlen rossz nap." },
        { label: "Napi naplóbejegyzések olvasása", desc: "A sparkline alatt a két legutóbbi nap ki van bővítve teljes válaszaikkal: gondolatok az edzés előtt, hogyan ment, mi ment jól, frusztrációk és fókusz a következő edzésre." },
        { label: "Hiányzó bejelentkezések", desc: "Bejegyzés nélküli napok (—) azt jelentik, hogy az atléta nem naplózott. Ha több egymást követő nap hiányzik, elkerülési magatartást vagy elkötelezettség hiányát jelezheti." },
      ] as Step[],
      note: { text: "Kereszt-ellenőrizd az edzésnaplót a naplóbejegyzésekkel. A 8/10-es hangulat egy edzésnapon ugyanazon nap negatív naplóbejegyzéssel párosítva gyakran azt jelenti, hogy az atléta fizikailag jól teljesít, de mentálisan küzd – árnyalt coaching pillanat." },
    },
    s06: {
      title: "Teszteredmények fül",
      subtitle: "SAT · ACSI · CSAI-2 · DAS",
      intro: "Amint egy atléta elvégzi és feloldja a tesztet, a pontszámolt eredmények automatikusan megjelennek itt. Tőled nem szükséges semmilyen lépés.",
      steps: [
        { label: "SAT – Sport Anxiety Test", desc: "Összpontszám 100-ból. Alacsonyabb a jobb. Ugrásokat a közelgő versenydátumokhoz viszonyítva vizsgálj." },
        { label: "ACSI – Coping Skills Inventory", desc: "Négy részpontszám: megbirkózás nehézségekkel, koncentráció, önbizalom és célkitűzés. Mindegyik százalékban kifejezve. Figyelj a legalacsonyabb értékre – ez általában az első coaching fókusz." },
        { label: "CSAI-2 – Competitive State Anxiety", desc: "Három pontszám: kognitív szorongás (aggodalom), szomatikus szorongás (testi tünetek) és önbizalom. Magas kognitív + alacsony önbizalom = klasszikus verseny előtti szorongásminta." },
        { label: "DAS – Depression, Anxiety, Stress", desc: "Szűri a depresszív gondolkodást, szorongást és stresszt. Magas DAS sok negatív naplóbejegyzéssel közvetlen beszélgetést és esetleges átirányítást igényelhet." },
      ] as Step[],
      note: { text: "A tesztek egyszeri atléta-fizetést igényelnek az eredmények feloldásához. Ha az eredmények nem jelennek meg, az atléta esetleg nem fejezte be a feloldási fizetést. Részleges vagy kifizetetlen eredményeket nem láthatsz." },
    },
    s07: {
      title: "Bejelentkezések fül",
      subtitle: "Heti és havi atléta önértékelések",
      steps: [
        { label: "Bejelentkezések megnyitása", desc: "Bontsd ki az atléta kártyát és érintsd meg a Bejelentkezések fület. Látni fogod a heti és havi beküldéseket, legújabbak először." },
        { label: "Mit mutat minden bejegyzés", desc: "Öt önértékelés (1–10): általános hangulat, edzésminőség, energiaszint, alvásminőség és felkészültség a következő hétre vagy hónapra." },
        { label: "Írásos reflexiók", desc: "Az értékelések alatt: az atléta legnagyobb sikere, fő kihívása és a következő hétre vagy hónapra vonatkozó fókusza. Olvasd ezeket a bejelentkezési hívások előtt – gyakran felszínre hozzák, mire fókuszál az atléta a legjobban." },
        { label: "Havi bejelentkezések", desc: "A havi beküldések három további kérdést tartalmaznak: legnagyobb áttörés, legfontosabb önismereti tanulság és szándék a következő hónapra." },
      ] as Step[],
      note: { text: "A bejelentkezési adatokat az edző nem szerkesztheti – az atléta olyannak küldi be, amilyen. Kereszt-ellenőrizd ugyanazon hét naplóbejegyzéseivel a teljes képhez." },
    },
    s08: {
      title: "Pszichológiai tesztek hozzárendelése",
      subtitle: "SAT · ACSI · CSAI-2 · DAS",
      steps: [
        { label: "Teszt hozzárendelése", desc: "Bontsd ki az atléta kártyát → Profil fül → görgess a teszthozzárendelési részhez. Válaszd a SAT, ACSI, CSAI-2 vagy DAS tesztet és érintsd meg a Hozzárendelés gombot. A teszt azonnal megjelenik kérdésként az atléta Eszközök fülén." },
        { label: "Az atléta elvégzi", desc: "Az atléta kiemelve látja a hozzárendelt tesztet az Eszközök fülén. Miután elvégzi és feloldja az eredményeket, a hozzárendelés automatikusan törlődik." },
        { label: "Eredmények megtekintése", desc: "A befejezett eredmények megjelennek az atléta Tesztpontszámok fülén. Az értékeket összevethetsd a napló-hangulattal – alacsony ACSI koncentráció negatív bejegyzések mellett verseny közelében erős korai figyelmeztető minta." },
        { label: "Mikor rendelj hozzá", desc: "Teszthozzárendeléssel strukturált pszichológiai alapvonalat kaphatsz a coaching elején. Rendelj hozzá újra, ha a naplóminták egy adott területet (szorongás, önbizalom, depresszió kockázat) jeleznek formális mérési igényt." },
      ] as Step[],
    },
    s09: {
      title: "Ego-State-ek – edző nézet",
      subtitle: "Az atléta pszichológiai személyiségei · Profil fül",
      steps: [
        { label: "Hol találhatók", desc: "Bontsd ki az atléta kártyát → Profil fül → görgess le. Ha az atléta feltérképezett ego-state-eket a Coach AI-n keresztül, minden elmentett state megjelenik nevével, területével és aktiválási rituáléjával." },
        { label: "Hogyan térképezik fel az atlétok", desc: "Az atlétok arra kérik a Coach AI-t, hogy vezessen ego-state feltérképező munkamenetet. Az AI nyolc kérdést tesz fel (név, szín, testtartás, testérzet, belső hang, eredet, terület, árnyékoldal, aktiválási rituálé) és az atléta elmenti a kapott state kártyát." },
        { label: "Alkalmazás a munkamenetekben", desc: "Hivatkozz az atléta state-jeire névvel a bejelentkezési hívásokban. Használd az árnyékoldal mezőt annak azonosítására, ha egy state rossz kontextusba kerül. Használd az aktiválási rituálét a verseny előtti felkészülés irányításában." },
        { label: "State konfliktusok", desc: "A leggyakoribb teljesítményprobléma a rossz state a rossz pillanatban – Elemző mód végrehajtás közben, Harcos mód regenerálódás közben. Ha ezt a mintát felismered a napló nyelvézetében, ez egy ego-state konfliktus, amelyet érdemes közvetlenül megnevezni." },
      ] as Step[],
    },
    s10: {
      title: "Gyors áttekintő",
      subtitle: "Irányítópult jelzések egy pillantásra",
      tableHeaders: ["Jelzés", "Mit jelent", "Javasolt lépés"] as [string, string, string],
      tableRows: [
        ["🟢 Pályán (55%+ pozitív)", "Az atléta következetesen pozitív mentalitást fejez ki", "Bejegyzések áttekintése, a működő megerősítése"],
        ["🟡 Figyelés (30–55% pozitív)", "Vegyes hangulat – lehet egy nehéz hét vagy trend", "Bejegyzések olvasása, edzésnapló hangulat ellenőrzése, üzenet küldése"],
        ["🔴 Figyelem (<30% pozitív)", "Túlnyomórészt negatív bejegyzések – az atléta küzd", "Vedd fel a kapcsolatot az atlétával közvetlenül a következő alkalom előtt"],
        ["0 bejegyzés ezen a héten", "Nincs napló aktivitás", "Emlékeztesd az atlétát a naplózásra – az elköteleződés az első lépés"],
        ["Hangulat esés (pl. 8 → 4/10)", "Hirtelen hangulatesés az edzésnaplóban", "Ellenőrizd az ugyanazon napokból való naplóbejegyzéseket a kontextushoz"],
        ["Alacsony ACSI Önbizalom <50%", "Önbizalom-hiány verseny kontextusban", "A következő alkalom fókuszát önbizalom-építő gyakorlatokra irányítsd"],
        ["Magas CSAI-2 kognitív szorongás", "Az atléta aggódik a teljesítmény eredményei miatt", "Gondolatstop vagy átkeretezési technikák bevezetése"],
        ["Bejelentkezési értékelések csökkennek", "Az atléta 5 önértékelése hétről hétre csökken", "Olvasd el az azonos heti írásos reflexiókat – gyakran magyarázzák a csökkenést"],
        ["Teszt hozzárendelve (függőben)", "Az atlétának van egy hozzárendelt tesztje, amelyet még nem végzett el", "Kövesd nyomon – a befejezés strukturált alapvonalat ad a jelzett területre"],
      ] as [string, string, string][],
      note: { bold: "Heti felülvizsgálati ritmus (javasolt):", text: " Ellenőrizd az összes atléta jelzést hetente egyszer az alkalmak előtt. Először olvasd el a teljes bejegyzéseket a 🔴 atlétáknál. Tekintsd át az edzésnapló hangulattrendeket az összes atlétánál. Jegyezd fel az utolsó felülvizsgálat óta megjelent teszteredményeket." },
    },
  },
} as const;

export type CoachContent = typeof coachContent.en;
