export type GuideLocale = "en" | "de" | "hu";
export type Step = { label: string; desc: string };
export type Note = { bold?: string; text: string };

export const athleteContent = {
  en: {
    back: "← Back to app",
    cover: {
      eyebrow: "PowerFlow · User Guide",
      title: ["Athlete", "Guide"],
      sub: "Everything you need to get the most out of the PowerFlow app — from signing in to logging your first training session and connecting with your coach.",
      signIn: "Sign in → app.power-flow.eu",
      meta: "Version 1.1 · May 2026 · app.power-flow.eu",
    },
    screens: {
      signIn: "Sign-in screen",
      onboardingStep1: "Step 1 — About you",
      onboardingMindset: "Step 4 — Mindset & self-rating",
      today: "Today screen",
      checkIn: "Training day check-in",
      journal: "Journal — write an entry",
      tools: "Tools — assessments",
      you: "You — profile & settings",
    },
    s00: {
      title: "Install the app",
      subtitle: "Add to Home Screen · No App Store needed",
      intro: "PowerFlow is a web app — nothing to download. Add it to your phone's home screen once and it opens full-screen like a native app, with push notifications and audio working correctly. Always open from the home screen icon, not from the browser.",
      ios: { title: "iPhone / iPad (Safari)", steps: ["Open the PowerFlow URL in Safari", "Tap the Share ↑ button at the bottom", "Scroll down and tap Add to Home Screen", "Tap Add in the top-right corner"] },
      android: { title: "Android (Chrome)", steps: ["Open the PowerFlow URL in Chrome", "Tap the ⋮ menu in the top-right corner", "Tap Add to Home Screen or Install app", "Tap Add or Install"] },
      note: { bold: "Tip:", text: " On iOS, only Safari supports Add to Home Screen — it will not work from Chrome or Firefox on iPhone." },
    },
    s01: {
      title: "Signing in",
      subtitle: "Google OAuth · Role selection",
      steps: [
        { label: "Open the app", desc: "Navigate to the PowerFlow URL. You will see the sign-in screen with a Google button." },
        { label: "Make sure Athlete is selected", desc: "Below the Google button you will see two role options: Athlete and Coach. The role is set permanently — choose Athlete." },
        { label: "Tap Sign in with Google", desc: "Complete the standard Google OAuth flow. You will be redirected to the setup wizard on first sign-in." },
        { label: "Used an invite link?", desc: "If your coach gave you a join link, open it before signing in. It automatically links your account to your coach." },
      ] as Step[],
      note: { bold: "Important:", text: " Your role (Athlete / Coach) is assigned at first sign-in and cannot be changed. If you accidentally signed in as a coach, contact support." },
    },
    s02: {
      title: "Setup wizard",
      subtitle: "6 steps · Replaces the paper application form",
      intro: "The wizard collects the same information as the PowerFlow application form and stores it securely in the app. All steps except Step 1 and Step 4's first question are optional — you can complete them later from the You tab.",
      steps: [
        { label: "Step 1 — About you", desc: "Full name (required), Instagram handle, and gender (required for GL Points calculation)." },
        { label: "Step 2 — Powerlifting profile", desc: "Years competing, federation, bodyweight, weight class, next competition date, and training days per week." },
        { label: "Step 3 — Your lifts", desc: "Current bests and competition goals for squat, bench, and deadlift in kg. Powers the GL Points calculator on the Today screen." },
        { label: "Step 4 — Mindset & self-assessment", desc: "Four open questions about your mental barriers, confidence, overthinking patterns, and previous coaching history. Then rate yourself 1–10 on five mental skills. This goes straight to your coach." },
        { label: "Step 5 — Goals", desc: "Three mental goals for the next 3 months, your expectations from coaching, mental tools you have tried before, and anything else important." },
        { label: "Step 6 — Your coach", desc: "Pick your PowerFlow coach from the list. Tap No coach yet if you want to connect later." },
      ] as Step[],
    },
    s03: {
      title: "Today — daily check-in",
      subtitle: "Log every session · Track your training week",
      steps: [
        { label: "Open Today tab", desc: "The Today tab is your home screen. At the top you will always see the check-in card if you have not logged yet today." },
        { label: "Choose Training Day or Rest Day", desc: "Tap the button that matches your day. A sheet slides up from the bottom." },
        { label: "Rate your mood (1–10)", desc: "Required. This powers the mood sparkline your coach sees in the training log." },
        { label: "Answer the training questions", desc: "On training days: thoughts before the session, how it went, what went well, any frustrations, and focus for next session. On rest days: just an optional note." },
        { label: "Tap Save", desc: "The check-in card turns green with a confirmation. Your coach can see this within seconds." },
        { label: "Edit any time", desc: "Tap Edit on the confirmation card to update your log for the same day." },
      ] as Step[],
      note: { bold: "Reminder badge:", text: " If you have not logged by end of day, a red dot appears on the Today tab. Enable browser notifications (tap 🔔 Reminders on the check-in card) to get a nudge at 7 pm." },
    },
    s04: {
      title: "Journal",
      subtitle: "Capture your mindset · AI sentiment & theme detection",
      steps: [
        { label: "Open Journal tab", desc: "Tap Journal in the bottom navigation. The entry composer is at the top." },
        { label: "Select a context tag", desc: "Choose from: General, Pre-competition, Post-competition, During session, or Rest day. This helps your coach filter entries." },
        { label: "Write freely", desc: "There is no minimum length. Describe what you are feeling, thinking, or observing about your mental state." },
        { label: "Tap Save entry", desc: "The entry is processed automatically. Sentiment (positive / neutral / negative) and themes (confidence, anxiety, focus, pressure, recovery…) are tagged by AI." },
        { label: "Review past entries", desc: "Scroll down to see all your entries, newest first. Sentiment is shown as a colour dot: green = positive, red = negative, grey = neutral." },
      ] as Step[],
      note: { text: "Journal entries feed directly into your coach's dashboard. Your weekly positive-sentiment rate and detected themes are the first things they see on your athlete card." },
    },
    s05: {
      title: "Tools — assessments",
      subtitle: "Four validated sport psychology tests",
      intro: "Complete these assessments periodically to track your psychological profile over time. Results appear on your coach's dashboard automatically.",
      steps: [
        { label: "SAT — Sport Anxiety Test", desc: "Measures your overall sport anxiety profile. ~10 minutes." },
        { label: "ACSI — Athletic Coping Skills Inventory", desc: "Assesses four coping skill areas: coping with adversity, concentration, confidence, and goal-setting." },
        { label: "CSAI-2 — Competitive State Anxiety Inventory", desc: "Differentiates cognitive anxiety (worry) from somatic anxiety (body tension) and self-confidence." },
        { label: "DAS — Depression, Anxiety & Stress Scale", desc: "Screens for depression-prone thinking, general anxiety, and stress levels adapted for athletes." },
      ] as Step[],
      note: { text: "Some tests require a one-time unlock payment to see your scored results. The test itself is always free to complete — payment is only needed to view the detailed breakdown and share it with your coach." },
    },
    s06: {
      title: "Course",
      subtitle: "16-week mental preparation programme",
      steps: [
        { label: "Unlock the course", desc: "Course access is granted by your coach. Once unlocked, the Course tab activates and the current week appears as a card on your Today screen." },
        { label: "Follow your competition timeline", desc: "The programme is calculated backwards from your competition date. Week 1 starts 16 weeks out, tapering to Week 16 in the final week before the meet." },
        { label: "Complete each week's content", desc: "Each week has three parts: a video lesson, a practical exercise, and a short Q&A. Progress dots show what is done." },
        { label: "Current week card", desc: "The Today screen shows your current course week as a reminder card. Tap Continue to jump straight into it." },
      ] as Step[],
      note: { text: "If you have not set a competition date, the course cannot calculate your current week. Add your meet date from the You tab first." },
    },
    s07: {
      title: "You — profile & settings",
      subtitle: "Update your data · Manage your coach connection",
      steps: [
        { label: "Open You tab", desc: "Tap You in the bottom navigation. All your profile data is editable here at any time." },
        { label: "Update your name", desc: "Tap the name field in the identity card at the top and save. This is the name your coach sees." },
        { label: "Update lifts and goals", desc: "Keep your current bests up to date so GL Points and the strength card on Today stay accurate." },
        { label: "Change competition date", desc: "Update your next competition date whenever plans change. This recalculates your training phase and course week." },
        { label: "Connect or change coach", desc: "In the Coach section, tap Choose a coach or Change coach to open the coach picker." },
        { label: "Enable notifications", desc: "A Notifications card shows your current permission status. If notifications are off, tap Enable to turn on daily check-in reminders. Once enabled, you will get a nudge at 7 pm on days you haven't logged yet." },
        { label: "Sign out", desc: "The Sign out button is at the bottom of the You page." },
      ] as Step[],
      note: { bold: "GL Points", text: " (IPF Goodlift formula) calculate automatically from your total (squat + bench + deadlift current bests) and bodyweight. Set your gender, bodyweight, and lifts to see them." },
    },
    s08: {
      title: "Coach AI",
      subtitle: "Sports psychology AI · Built on your coach's methodology",
      steps: [
        { label: "Open Coach AI", desc: "Tap the chat bubble icon in the bottom navigation. The first time you open it with no conversation history, personalised prompt chips appear based on your recent journal entries, upcoming meet date, and what you've already mapped." },
        { label: "What you can ask it", desc: "Analyse recent journal entries · Prepare mentally for competition · Debrief a tough session · Map your ego states · Generate a visualization or relaxation script · Guide you through switching psychological states · Work through self-doubt or anxiety" },
        { label: "Scripts in your coach's voice", desc: "Any script the AI generates — visualization, grounding, pre-competition routine — can be played back in your coach's voice. Tap ▶ Play on the script card. Save scripts to your library with the save button to listen again any time." },
        { label: "Smart prompts", desc: "If you open Coach AI without typing anything, personalised prompt chips appear. These update based on your recent entries, upcoming meet, and ego states. Tap one to start the session immediately." },
      ] as Step[],
      note: { text: "Coach AI works best when your journal is active. The more you write, the more context the AI has — and the more relevant its observations and suggestions become." },
    },
    s09: {
      title: "Ego States",
      subtitle: "Psychological personas · Deliberate state design",
      intro: "An ego state is a psychological persona you deliberately step into for a specific context. Each state has eight components:",
      table: [
        ["Name", "What you call this part of you — e.g. The Machine, The Builder"],
        ["Colour", "A visual anchor for rapid recognition"],
        ["Posture", "How your body holds itself when fully in this state"],
        ["Body feeling", "Where you feel this state in your body, and what it feels like"],
        ["Inner voice", "The tone, speed, and style of how this state speaks internally"],
        ["Origin", "When was this state born? What situation created it?"],
        ["Domain", "What contexts call for this state?"],
        ["Shadow side", "What does it look like when this state shows up at the wrong moment?"],
        ["Activation ritual", "Three concrete steps to switch into this state intentionally"],
      ] as [string, string][],
      steps: [
        { label: "Map via Coach AI", desc: "Ask Coach AI: 'Map my ego states with me.' It asks eight questions one at a time, then outputs a state card you save with one tap." },
        { label: "Review in You tab", desc: "Once saved, an Ego States section appears in your You tab. Tap it to view, edit, or add states." },
        { label: "Practise switching", desc: "The skill is recognising which state a moment calls for and entering it via your activation ritual — before the moment demands it. Thinking-mode during execution causes paralysis. Warrior-mode during recovery causes burnout." },
      ] as Step[],
    },
    s10: {
      title: "Weekly & monthly check-ins",
      subtitle: "Structured reflection · Coach visibility",
      steps: [
        { label: "Weekly check-in", desc: "A prompt appears at the end of each week. Rate five areas: overall mood, training quality, energy levels, sleep quality, and readiness for next week (each 1–10). Then add your biggest win, main challenge, and one focus for the week ahead. Takes about 60 seconds." },
        { label: "Monthly check-in", desc: "Appears at the end of each month with the same five ratings plus three deeper questions: biggest breakthrough this month, the most important thing you learned about yourself, and your main intention going into next month." },
        { label: "Coach visibility", desc: "Your coach sees all check-in responses on their dashboard. These give them a structured picture of how each week and month felt — beyond the individual training log entries." },
      ] as Step[],
      note: { text: "Check-ins are separate from your daily journal and training log. They are a weekly and monthly pulse — the bigger picture sitting above the day-to-day entries." },
    },
    ref: {
      title: "Quick reference",
      subtitle: "What each tab does at a glance",
      headers: ["Tab", "What it does", "Use it for"] as [string, string, string],
      rows: [
        ["Today", "Daily check-in, phase countdown, lift goals, course card", "Every single day — start here"],
        ["Journal", "Free-text entries, AI sentiment & theme tagging", "After sessions, competitions, or whenever something is on your mind"],
        ["Tools", "Sport psychology assessments (SAT, ACSI, CSAI-2, DAS)", "At start of programme and periodically to track progress"],
        ["Coach AI", "Sports psychology AI, script generation, ego state mapping", "Before competition, after tough sessions, whenever you need to work something through"],
        ["Course", "16-week structured mental programme", "Weekly — follow the current week's content"],
        ["You", "Profile editor, lifts, goals, coach, ego states, sign out", "Whenever your data changes or after mapping a new ego state"],
      ] as [string, string, string][],
    },
  },

  de: {
    back: "← Zurück zur App",
    cover: {
      eyebrow: "PowerFlow · Benutzerhandbuch",
      title: ["Athleten", "Leitfaden"],
      sub: "Alles, was du brauchst, um das Beste aus der PowerFlow-App herauszuholen – vom Anmelden bis zum ersten Training und der Verbindung mit deinem Coach.",
      signIn: "Anmelden → app.power-flow.eu",
      meta: "Version 1.1 · May 2026 · app.power-flow.eu",
    },
    screens: {
      signIn: "Anmeldebildschirm",
      onboardingStep1: "Schritt 1 — Über dich",
      onboardingMindset: "Schritt 4 — Mentalität & Selbsteinschätzung",
      today: "Heute-Bildschirm",
      checkIn: "Trainingstag Check-in",
      journal: "Journal — Eintrag schreiben",
      tools: "Tools — Assessments",
      you: "Ich — Profil & Einstellungen",
    },
    s00: {
      title: "App installieren",
      subtitle: "Zum Startbildschirm hinzufügen · Kein App Store nötig",
      intro: "PowerFlow ist eine Web-App – kein Download erforderlich. Füge sie einmal zum Startbildschirm deines Handys hinzu und sie öffnet sich vollständig wie eine native App, mit Push-Benachrichtigungen und Audio. Öffne die App immer über das Startbildschirm-Symbol, nicht über den Browser.",
      ios: { title: "iPhone / iPad (Safari)", steps: ["Öffne die PowerFlow-URL in Safari", "Tippe unten auf den Teilen ↑ Button", "Scrolle nach unten und tippe Zum Home-Bildschirm", "Tippe oben rechts auf Hinzufügen"] },
      android: { title: "Android (Chrome)", steps: ["Öffne die PowerFlow-URL in Chrome", "Tippe auf das ⋮ Menü oben rechts", "Tippe Zum Startbildschirm hinzufügen oder App installieren", "Tippe Hinzufügen oder Installieren"] },
      note: { bold: "Tipp:", text: " Auf iOS unterstützt nur Safari das Hinzufügen zum Startbildschirm – bei Chrome oder Firefox auf dem iPhone funktioniert es nicht." },
    },
    s01: {
      title: "Anmelden",
      subtitle: "Google OAuth · Rollenauswahl",
      steps: [
        { label: "App öffnen", desc: "Navigiere zur PowerFlow-URL. Du siehst den Anmeldebildschirm mit einem Google-Button." },
        { label: "Athlete auswählen", desc: "Unter dem Google-Button siehst du zwei Rollenoptionen: Athlete und Coach. Die Rolle ist dauerhaft – wähle Athlete." },
        { label: "Mit Google anmelden tippen", desc: "Schließe den Google-OAuth-Prozess ab. Du wirst beim ersten Anmelden zum Einrichtungsassistenten weitergeleitet." },
        { label: "Einladungslink erhalten?", desc: "Falls dein Coach dir einen Einladungslink gegeben hat, öffne ihn vor dem Anmelden. Er verknüpft dein Konto automatisch mit deinem Coach." },
      ] as Step[],
      note: { bold: "Wichtig:", text: " Deine Rolle (Athlete / Coach) wird beim ersten Anmelden vergeben und kann nicht geändert werden. Falls du dich versehentlich als Coach angemeldet hast, wende dich an den Support." },
    },
    s02: {
      title: "Einrichtungsassistent",
      subtitle: "6 Schritte · Ersetzt das Papier-Antragsformular",
      intro: "Der Assistent sammelt dieselben Informationen wie das PowerFlow-Antragsformular und speichert sie sicher in der App. Alle Schritte außer Schritt 1 und die erste Frage in Schritt 4 sind optional – du kannst sie später über den Tab Ich vervollständigen.",
      steps: [
        { label: "Schritt 1 – Über dich", desc: "Vollständiger Name (Pflichtfeld), Instagram-Handle und Geschlecht (Pflichtfeld für GL-Punkte-Berechnung)." },
        { label: "Schritt 2 – Powerlifting-Profil", desc: "Jahre im Wettkampf, Verband, Körpergewicht, Gewichtsklasse, nächster Wettkampftermin und Trainingstage pro Woche." },
        { label: "Schritt 3 – Deine Lifte", desc: "Aktuelle Bestleistungen und Wettkampfziele für Kniebeuge, Bankdrücken und Kreuzheben in kg. Wird für den GL-Punkte-Rechner auf dem Heute-Bildschirm verwendet." },
        { label: "Schritt 4 – Mentalität und Selbsteinschätzung", desc: "Vier offene Fragen zu mentalen Hindernissen, Selbstvertrauen, Grübeln und früherer Coaching-Erfahrung. Dann bewertest du dich 1–10 in fünf mentalen Bereichen. Das geht direkt an deinen Coach." },
        { label: "Schritt 5 – Ziele", desc: "Drei mentale Ziele für die nächsten 3 Monate, deine Erwartungen ans Coaching, bereits ausprobierte Techniken und weitere wichtige Informationen." },
        { label: "Schritt 6 – Dein Coach", desc: "Wähle deinen PowerFlow-Coach aus der Liste. Tippe Noch kein Coach, falls du später verbinden möchtest." },
      ] as Step[],
    },
    s03: {
      title: "Heute – Tägliches Check-in",
      subtitle: "Jede Einheit loggen · Trainingswoche verfolgen",
      steps: [
        { label: "Tab Heute öffnen", desc: "Der Heute-Tab ist dein Startbildschirm. Oben siehst du immer die Check-in-Karte, wenn du heute noch nichts geloggt hast." },
        { label: "Trainings- oder Ruhetag wählen", desc: "Tippe die Schaltfläche, die zu deinem Tag passt. Ein Blatt erscheint von unten." },
        { label: "Stimmung bewerten (1–10)", desc: "Pflichtfeld. Dieser Wert erscheint in der Stimmungs-Sparkline, die dein Coach im Trainingsprotokoll sieht." },
        { label: "Trainingsfragen beantworten", desc: "An Trainingstagen: Gedanken vor der Einheit, wie es lief, was gut war, Frustration und Fokus für die nächste Einheit. An Ruhetagen: nur eine optionale Notiz." },
        { label: "Speichern tippen", desc: "Die Check-in-Karte wird grün und zeigt eine Bestätigung. Dein Coach sieht das innerhalb von Sekunden." },
        { label: "Jederzeit bearbeiten", desc: "Tippe Bearbeiten auf der Bestätigungskarte, um deinen Eintrag für denselben Tag zu aktualisieren." },
      ] as Step[],
      note: { bold: "Erinnerungs-Badge:", text: " Falls du bis zum Abend nichts geloggt hast, erscheint ein roter Punkt auf dem Heute-Tab. Aktiviere Browser-Benachrichtigungen (tippe 🔔 Erinnerungen), um um 19:00 Uhr erinnert zu werden." },
    },
    s04: {
      title: "Journal",
      subtitle: "Gedanken festhalten · KI-Sentiment und Themen",
      steps: [
        { label: "Tab Journal öffnen", desc: "Tippe auf Journal in der unteren Navigation. Oben findest du den Editor für neue Einträge." },
        { label: "Kontext-Tag auswählen", desc: "Wähle aus: Allgemein, Vor dem Wettkampf, Nach dem Wettkampf, Während der Einheit oder Ruhetag. Das hilft deinem Coach beim Filtern." },
        { label: "Frei schreiben", desc: "Es gibt keine Mindestlänge. Beschreibe, was du fühlst, denkst oder über deinen mentalen Zustand beobachtest." },
        { label: "Eintrag speichern tippen", desc: "Der Eintrag wird automatisch verarbeitet. Sentiment (positiv / neutral / negativ) und Themen (Selbstvertrauen, Angst, Fokus, Druck, Erholung…) werden von der KI getaggt." },
        { label: "Vergangene Einträge ansehen", desc: "Scrolle nach unten, um alle Einträge zu sehen – neueste zuerst. Sentiment wird als farbiger Punkt angezeigt: grün = positiv, rot = negativ, grau = neutral." },
      ] as Step[],
      note: { text: "Journaleinträge fließen direkt ins Dashboard deines Coaches. Deine wöchentliche Positiv-Sentiment-Rate und erkannte Themen sind das Erste, was dein Coach auf deiner Athleten-Karte sieht." },
    },
    s05: {
      title: "Tools – Assessments",
      subtitle: "Vier validierte sportpsychologische Tests",
      intro: "Führe diese Assessments regelmäßig durch, um dein psychologisches Profil im Zeitverlauf zu verfolgen. Ergebnisse erscheinen automatisch im Dashboard deines Coaches.",
      steps: [
        { label: "SAT – Sport Anxiety Test", desc: "Misst dein allgemeines Sportangst-Profil. Ca. 10 Minuten." },
        { label: "ACSI – Athletic Coping Skills Inventory", desc: "Bewertet vier Bewältigungsbereiche: Umgang mit Rückschlägen, Konzentration, Selbstvertrauen und Zielsetzung." },
        { label: "CSAI-2 – Competitive State Anxiety Inventory", desc: "Unterscheidet kognitive Angst (Sorgen) von somatischer Angst (Körperspannung) und Selbstvertrauen." },
        { label: "DAS – Depression, Anxiety & Stress Scale", desc: "Screent auf depressives Denken, allgemeine Angst und Stressniveaus – angepasst für Athleten." },
      ] as Step[],
      note: { text: "Für einige Tests ist eine einmalige Freischaltgebühr erforderlich, um deine Bewertungsergebnisse zu sehen. Der Test selbst ist immer kostenlos – die Zahlung ist nur für die detaillierte Auswertung nötig." },
    },
    s06: {
      title: "Kurs",
      subtitle: "16-wöchiges mentales Vorbereitungsprogramm",
      steps: [
        { label: "Kurs freischalten", desc: "Der Kurszugang wird von deinem Coach gewährt. Sobald er freigeschaltet ist, wird der Kurs-Tab aktiv und die aktuelle Woche erscheint als Karte auf deinem Heute-Bildschirm." },
        { label: "Wettkampfplanung folgen", desc: "Das Programm wird rückwärts von deinem Wettkampftermin berechnet. Woche 1 beginnt 16 Wochen vorher, bis hin zu Woche 16 in der letzten Woche vor dem Wettkampf." },
        { label: "Wocheninhalte abschließen", desc: "Jede Woche besteht aus drei Teilen: ein Video-Lernmodul, eine praktische Übung und ein kurzes Q&A. Fortschrittspunkte zeigen, was erledigt ist." },
        { label: "Aktuelle Wochenkarte", desc: "Der Heute-Bildschirm zeigt deine aktuelle Kurswoche als Erinnerungskarte. Tippe Weiter, um direkt dorthin zu springen." },
      ] as Step[],
      note: { text: "Ohne festgelegten Wettkampftermin kann der Kurs deine aktuelle Woche nicht berechnen. Füge zuerst dein Meet-Datum im Tab Ich hinzu." },
    },
    s07: {
      title: "Ich – Profil & Einstellungen",
      subtitle: "Daten aktualisieren · Coach-Verbindung verwalten",
      steps: [
        { label: "Tab Ich öffnen", desc: "Tippe auf Ich in der unteren Navigation. Alle Profildaten können hier jederzeit bearbeitet werden." },
        { label: "Namen aktualisieren", desc: "Tippe auf das Namensfeld in der Identitätskarte oben und speichere. Das ist der Name, den dein Coach sieht." },
        { label: "Lifte und Ziele aktualisieren", desc: "Halte deine aktuellen Bestleistungen auf dem neuesten Stand, damit GL-Punkte und die Stärkekarte auf Heute korrekt bleiben." },
        { label: "Wettkampftermin ändern", desc: "Aktualisiere deinen nächsten Wettkampftermin, wenn sich Pläne ändern. Das berechnet deine Trainingsphase und Kurswoche neu." },
        { label: "Coach verbinden oder wechseln", desc: "Im Coach-Bereich tippst du auf Coach auswählen oder Coach wechseln, um den Coach-Auswahldialog zu öffnen." },
        { label: "Benachrichtigungen aktivieren", desc: "Eine Benachrichtigungskarte zeigt deinen aktuellen Berechtigungsstatus. Falls Benachrichtigungen deaktiviert sind, tippe auf Aktivieren, um tägliche Check-in-Erinnerungen einzuschalten. Wenn du an einem Tag nichts geloggt hast, erhältst du um 19:00 Uhr eine Erinnerung." },
        { label: "Abmelden", desc: "Der Abmelden-Button befindet sich unten auf der Ich-Seite." },
      ] as Step[],
      note: { bold: "GL-Punkte", text: " (IPF Goodlift-Formel) werden automatisch aus deinem Total (Kniebeuge + Bankdrücken + Kreuzheben aktuelle Bestleistungen) und Körpergewicht berechnet. Stelle Geschlecht, Körpergewicht und Lifte ein, um sie zu sehen." },
    },
    s08: {
      title: "Coach AI",
      subtitle: "Sport-Psychologie-KI · Basiert auf der Methodik deines Coaches",
      steps: [
        { label: "Coach AI öffnen", desc: "Tippe auf das Chat-Symbol in der unteren Navigation. Beim ersten Öffnen ohne Gesprächsverlauf erscheinen personalisierte Prompt-Chips basierend auf deinen letzten Journaleinträgen, dem bevorstehenden Meet und deinen gemappten Ego-States." },
        { label: "Was du fragen kannst", desc: "Letzte Journaleinträge analysieren · Mental auf Wettkämpfe vorbereiten · Schwierige Einheiten debriefing · Ego-States mappen · Visualisierungs- oder Entspannungsskripte erstellen · Psychologische Zustände wechseln · Selbstzweifel oder Angst verarbeiten" },
        { label: "Skripte in der Stimme deines Coaches", desc: "Jedes KI-Skript – Visualisierung, Erdung, Wettkampfvorbereitung – kann in der Stimme deines Coaches abgespielt werden. Tippe ▶ Abspielen auf der Skriptkarte. Speichere Skripte in deiner Bibliothek, um sie jederzeit wieder zu hören." },
        { label: "Intelligente Prompts", desc: "Wenn du Coach AI ohne Eingabe öffnest, erscheinen personalisierte Prompt-Chips. Diese werden basierend auf deinen letzten Einträgen, dem bevorstehenden Meet und Ego-States aktualisiert. Tippe einen an, um die Sitzung sofort zu starten." },
      ] as Step[],
      note: { text: "Coach AI funktioniert am besten, wenn dein Journal aktiv ist. Je mehr du schreibst, desto mehr Kontext hat die KI – und desto relevanter werden ihre Beobachtungen und Vorschläge." },
    },
    s09: {
      title: "Ego-States",
      subtitle: "Psychologische Personas · Bewusstes Zustandsdesign",
      intro: "Ein Ego-State ist eine psychologische Persona, die du bewusst für einen bestimmten Kontext einnimmst. Jeder State hat acht Komponenten:",
      table: [
        ["Name", "Wie du diesen Teil von dir nennst – z.B. Die Maschine, Der Erbauer"],
        ["Farbe", "Ein visueller Anker zur schnellen Erkennung"],
        ["Haltung", "Wie dein Körper sich hält, wenn du vollständig in diesem State bist"],
        ["Körpergefühl", "Wo du diesen State in deinem Körper spürst und wie er sich anfühlt"],
        ["Innere Stimme", "Ton, Geschwindigkeit und Stil, wie dieser State intern spricht"],
        ["Ursprung", "Wann wurde dieser State geboren? Welche Situation hat ihn geschaffen?"],
        ["Domäne", "Welche Kontexte rufen diesen State ab?"],
        ["Schattenseite", "Wie sieht es aus, wenn dieser State im falschen Moment auftaucht?"],
        ["Aktivierungsritual", "Drei konkrete Schritte, um bewusst in diesen State zu wechseln"],
      ] as [string, string][],
      steps: [
        { label: "Via Coach AI mappen", desc: "Frage Coach AI: 'Mappe meine Ego-States mit mir.' Die KI stellt acht Fragen nacheinander und gibt dann eine State-Karte aus, die du mit einem Tippen speicherst." },
        { label: "Im Tab Ich ansehen", desc: "Nach dem Speichern erscheint ein Ego-States-Bereich in deinem Tab Ich. Tippe darauf, um States anzusehen, zu bearbeiten oder hinzuzufügen." },
        { label: "Wechseln üben", desc: "Die Fähigkeit besteht darin zu erkennen, welcher State ein Moment erfordert, und ihn über dein Aktivierungsritual einzunehmen – bevor der Moment es fordert. Denk-Modus während der Ausführung führt zu Lähmung. Krieger-Modus in der Erholung führt zu Burnout." },
      ] as Step[],
    },
    s10: {
      title: "Wöchentliche & monatliche Check-ins",
      subtitle: "Strukturierte Reflexion · Coach-Sichtbarkeit",
      steps: [
        { label: "Wöchentliches Check-in", desc: "Am Ende jeder Woche erscheint eine Aufforderung. Bewerte fünf Bereiche: Gesamtstimmung, Trainingsqualität, Energielevel, Schlafqualität und Bereitschaft für die nächste Woche (je 1–10). Dann füge deinen größten Erfolg, die Hauptherausforderung und einen Fokus hinzu. Dauert ca. 60 Sekunden." },
        { label: "Monatliches Check-in", desc: "Erscheint am Ende jedes Monats mit denselben fünf Bewertungen plus drei tiefere Fragen: größter Durchbruch dieses Monats, wichtigste Erkenntnis über dich selbst und deine Intention für den nächsten Monat." },
        { label: "Coach-Sichtbarkeit", desc: "Dein Coach sieht alle Check-in-Antworten auf seinem Dashboard. Diese geben ihm ein strukturiertes Bild davon, wie sich jede Woche und jeder Monat angefühlt hat." },
      ] as Step[],
      note: { text: "Check-ins sind getrennt von deinem täglichen Journal und Trainingsprotokoll. Sie sind ein wöchentlicher und monatlicher Puls – das große Bild über den alltäglichen Einträgen." },
    },
    ref: {
      title: "Kurzreferenz",
      subtitle: "Was jeder Tab auf einen Blick macht",
      headers: ["Tab", "Was er macht", "Wofür nutzen"] as [string, string, string],
      rows: [
        ["Heute", "Tägliches Check-in, Phasen-Countdown, Lift-Ziele, Kurskarte", "Jeden Tag – hier beginnen"],
        ["Journal", "Freitext-Einträge, KI-Sentiment und Themen-Tagging", "Nach Einheiten, Wettkämpfen oder wann immer etwas auf dem Herzen liegt"],
        ["Tools", "Sportpsychologische Assessments (SAT, ACSI, CSAI-2, DAS)", "Zu Beginn des Programms und periodisch, um den Fortschritt zu verfolgen"],
        ["Coach AI", "Sport-Psychologie-KI, Skripterstellung, Ego-State-Mapping", "Vor Wettkämpfen, nach schwierigen Einheiten, wann immer du etwas durcharbeiten musst"],
        ["Kurs", "16-wöchiges strukturiertes mentales Programm", "Wöchentlich – aktuelle Wocheninhalte folgen"],
        ["Ich", "Profileditor, Lifte, Ziele, Coach, Ego-States, Abmelden", "Wenn sich deine Daten ändern oder nach dem Mappen eines neuen Ego-States"],
      ] as [string, string, string][],
    },
  },

  hu: {
    back: "← Vissza az appba",
    cover: {
      eyebrow: "PowerFlow · Felhasználói kézikönyv",
      title: ["Atléta", "Kézikönyv"],
      sub: "Minden, ami szükséges a PowerFlow app teljes kihasználásához – a bejelentkezéstől az első edzés naplózásáig és az edződdel való kapcsolódásig.",
      signIn: "Bejelentkezés → app.power-flow.eu",
      meta: "1.1 verzió · 2026. május · app.power-flow.eu",
    },
    screens: {
      signIn: "Bejelentkezési képernyő",
      onboardingStep1: "1. lépés — Rólad",
      onboardingMindset: "4. lépés — Mentalitás & önértékelés",
      today: "Ma képernyő",
      checkIn: "Edzésnap bejelentkezés",
      journal: "Napló — bejegyzés írása",
      tools: "Eszközök — felmérések",
      you: "Én — profil & beállítások",
    },
    s00: {
      title: "Az app telepítése",
      subtitle: "Hozzáadás a főképernyőhöz · Nincs szükség App Store-ra",
      intro: "A PowerFlow egy webalkalmazás – nincs mit letölteni. Add hozzá a telefon főképernyőjéhez egyszer, és teljes képernyőn nyílik meg, mint egy natív app, push értesítésekkel és hanggal. Mindig a főképernyő ikonból nyisd meg, ne a böngészőből.",
      ios: { title: "iPhone / iPad (Safari)", steps: ["Nyisd meg a PowerFlow URL-t Safariban", "Érintsd meg a Megosztás ↑ gombot alul", "Görgess le és érintsd meg a Főképernyőre adás lehetőséget", "Érintsd meg a Hozzáadás gombot jobb felül"] },
      android: { title: "Android (Chrome)", steps: ["Nyisd meg a PowerFlow URL-t Chrome-ban", "Érintsd meg a ⋮ menüt jobb felül", "Érintsd meg a Hozzáadás a főképernyőhöz vagy App telepítése lehetőséget", "Érintsd meg a Hozzáadás vagy Telepítés gombot"] },
      note: { bold: "Tipp:", text: " iOS-en csak a Safari támogatja a főképernyőre adást – iPhone-on Chrome vagy Firefox böngészőből ez nem működik." },
    },
    s01: {
      title: "Bejelentkezés",
      subtitle: "Google OAuth · Szerepválasztás",
      steps: [
        { label: "Nyisd meg az appot", desc: "Navigálj a PowerFlow URL-re. A bejelentkezési képernyőn egy Google gombot fogsz látni." },
        { label: "Válaszd az Atléta szerepkört", desc: "A Google gomb alatt két szerepkör jelenik meg: Atléta és Edző. A szerepkör végleges – válaszd az Atléta opciót." },
        { label: "Érintsd meg a Bejelentkezés Google-lal gombot", desc: "Hajtsd végre a szokásos Google OAuth folyamatot. Első bejelentkezéskor a beállítási varázslóhoz irányít az app." },
        { label: "Kaptál meghívó linket?", desc: "Ha az edződ meghívó linket adott, nyisd meg azt a bejelentkezés előtt. Ez automatikusan összeköti a fiókod az edződdel." },
      ] as Step[],
      note: { bold: "Fontos:", text: " A szerepköröd (Atléta / Edző) az első bejelentkezéskor kerül beállításra és nem módosítható. Ha véletlenül edzőként jelentkeztél be, vedd fel a kapcsolatot a támogatással." },
    },
    s02: {
      title: "Beállítási varázsló",
      subtitle: "6 lépés · Helyettesíti a papíros jelentkezési lapot",
      intro: "A varázsló ugyanazokat az adatokat gyűjti, mint a PowerFlow jelentkezési lap, és biztonságosan tárolja azokat az appban. Az 1. lépésen és a 4. lépés első kérdésén kívül minden opcionális – később is kitöltheted az Én fülről.",
      steps: [
        { label: "1. lépés – Rólad", desc: "Teljes név (kötelező), Instagram felhasználónév és nem (kötelező a GL-pontok számításához)." },
        { label: "2. lépés – Erőemelés profil", desc: "Versenyévek száma, szövetség, testtömeg, súlycsoport, következő verseny időpontja és heti edzésnapok száma." },
        { label: "3. lépés – Emeléseid", desc: "Jelenlegi személyes rekordok és versenyeredmény-célok guggolásra, fekvenyomásra és elhúzásra kg-ban. Ez táplálja a GL-pontok számítóját a Ma képernyőn." },
        { label: "4. lépés – Mentalitás és önértékelés", desc: "Négy nyitott kérdés a mentális akadályokról, önbizalomról, túlgondolkodási szokásokról és korábbi edzői tapasztalatokról. Aztán értékeld magad 1–10-es skálán öt mentális készség terén. Ez egyenesen az edződhöz kerül." },
        { label: "5. lépés – Célok", desc: "Három mentális cél a következő 3 hónapra, elvárásaid az edzéssel kapcsolatban, korábban kipróbált technikák és egyéb fontos információk." },
        { label: "6. lépés – Az edződ", desc: "Válaszd ki a PowerFlow edződet a listából. Érintsd meg a Még nincs edzőm opciót, ha később szeretnél kapcsolódni." },
      ] as Step[],
    },
    s03: {
      title: "Ma – napi bejelentkezés",
      subtitle: "Minden edzés naplózása · Edzéshét nyomon követése",
      steps: [
        { label: "Nyisd meg a Ma fület", desc: "A Ma fül a kezdőképernyőd. Felül mindig látod a bejelentkezési kártyát, ha még nem naplóztál ma." },
        { label: "Válassz edzésnapot vagy pihenőnapot", desc: "Érintsd meg a napodhoz illő gombot. Egy lap csúszik fel alulról." },
        { label: "Értékeld a hangulatod (1–10)", desc: "Kötelező mező. Ez táplálja a hangulat-sparkline-t, amelyet az edződ lát az edzésnaplóban." },
        { label: "Válaszolj az edzéses kérdésekre", desc: "Edzésnapokon: gondolatok az edzés előtt, hogyan ment, mi ment jól, mi okozott frusztrációt és fókusz a következő edzésre. Pihenőnapokon: csak egy opcionális megjegyzés." },
        { label: "Érintsd meg a Mentés gombot", desc: "A bejelentkezési kártya zöldre vált és megerősítést jelenít meg. Az edződ másodperceken belül látja ezt." },
        { label: "Bármikor szerkeszthető", desc: "Érintsd meg a Szerkesztés gombot a megerősítő kártyán, hogy frissítsd az aznapi naplódat." },
      ] as Step[],
      note: { bold: "Emlékeztető jelvény:", text: " Ha napvégéig nem naplóztál, egy piros pont jelenik meg a Ma fülön. Engedélyezd a böngésző értesítéseket (érintsd meg a 🔔 Emlékeztetők gombot), hogy este 7-kor figyelmeztetést kapj." },
    },
    s04: {
      title: "Napló",
      subtitle: "Gondolatok rögzítése · AI-hangulatelemzés és témák",
      steps: [
        { label: "Nyisd meg a Napló fület", desc: "Érintsd meg a Napló gombot az alsó navigációban. Az újbejegyzés szerkesztő felül található." },
        { label: "Válassz kontextus-címkét", desc: "Válaszd: Általános, Verseny előtt, Verseny után, Edzés közben vagy Pihenőnap. Ez segít az edzőnek a szűrésben." },
        { label: "Írj szabadon", desc: "Nincs minimum hossz. Írd le, mit érzel, gondolsz vagy észlelsz a mentális állapotodról." },
        { label: "Érintsd meg a Bejegyzés mentése gombot", desc: "A bejegyzés automatikusan feldolgozódik. Az AI megjelöli a hangulatot (pozitív / semleges / negatív) és a témákat (önbizalom, szorongás, fókusz, nyomás, regenerálódás…)." },
        { label: "Korábbi bejegyzések megtekintése", desc: "Görgesd le az összes bejegyzés megtekintéséhez – a legújabbak először. A hangulat színes pontként jelenik meg: zöld = pozitív, piros = negatív, szürke = semleges." },
      ] as Step[],
      note: { text: "A naplóbejegyzések közvetlenül az edződ irányítópultjára kerülnek. A heti pozitív hangulat aránya és a felismert témák az első dolgok, amelyeket az edződ lát az atléta kártyádon." },
    },
    s05: {
      title: "Eszközök – felmérések",
      subtitle: "Négy validált sportpszichológiai teszt",
      intro: "Végezd el ezeket a felméréseket rendszeresen, hogy nyomon követhesd a pszichológiai profilodat idővel. Az eredmények automatikusan megjelennek az edződ irányítópultján.",
      steps: [
        { label: "SAT – Sport Anxiety Test", desc: "Méri az általános sportazorongás profilodat. ~10 perc." },
        { label: "ACSI – Athletic Coping Skills Inventory", desc: "Négy megküzdési területet értékel: megbirkózás a nehézségekkel, koncentráció, önbizalom és célkitűzés." },
        { label: "CSAI-2 – Competitive State Anxiety Inventory", desc: "Megkülönbözteti a kognitív szorongást (aggodalom) a szomatikus szorongástól (testi feszültség) és az önbizalomtól." },
        { label: "DAS – Depression, Anxiety & Stress Scale", desc: "Szűri a depresszív gondolkodást, általános szorongást és stressz szinteket – sportolókhoz igazítva." },
      ] as Step[],
      note: { text: "Egyes tesztek egyszeri feloldási díjat igényelnek a pontszámolt eredmények megtekintéséhez. Maga a teszt mindig ingyenes – a fizetés csak a részletes kiértékeléshez és az edződdel való megosztáshoz szükséges." },
    },
    s06: {
      title: "Tanfolyam",
      subtitle: "16 hetes mentális felkészítő program",
      steps: [
        { label: "Tanfolyam feloldása", desc: "A tanfolyamhoz való hozzáférést az edződ adja meg. Az aktiválás után a Tanfolyam fül aktívvá válik, és az aktuális hét kártyaként megjelenik a Ma képernyőn." },
        { label: "Kövesd a verseny menetrendet", desc: "A program a versenynapodtól visszafelé számolódik. Az 1. hét 16 héttel a verseny előtt kezdődik, egészen a 16. hétig az utolsó verseny előtti héten." },
        { label: "Teljesítsd a heti tartalmakat", desc: "Minden hétnek három része van: egy videólecke, egy gyakorlati feladat és egy rövid kérdés-felelet. A haladáspöttyök mutatják, mi van kész." },
        { label: "Aktuális heti kártya", desc: "A Ma képernyő emlékeztető kártyaként mutatja az aktuális tanfolyami hetet. Érintsd meg a Folytatás gombot, hogy egyenesen oda ugorj." },
      ] as Step[],
      note: { text: "Versenyidőpont nélkül a tanfolyam nem tudja kiszámítani az aktuális hetedet. Először add meg a versenyed időpontját az Én fülön." },
    },
    s07: {
      title: "Én – profil és beállítások",
      subtitle: "Adatok frissítése · Edzőkapcsolat kezelése",
      steps: [
        { label: "Nyisd meg az Én fület", desc: "Érintsd meg az Én gombot az alsó navigációban. Az összes profiladat itt bármikor szerkeszthető." },
        { label: "Frissítsd a neved", desc: "Érintsd meg a névmezőt a felső identitáskártyán és mentsd el. Ez a név, amelyet az edződ lát." },
        { label: "Frissítsd az emeléseket és célokat", desc: "Tartsd naprakészen a jelenlegi személyes rekordjaidat, hogy a GL-pontok és az erőkártya a Ma képernyőn pontosak maradjanak." },
        { label: "Versenyidőpont módosítása", desc: "Frissítsd a következő versenyed időpontját, amikor a tervek változnak. Ez újraszámítja az edzési fázisod és tanfolyami hetedet." },
        { label: "Edző csatlakoztatása vagy váltás", desc: "Az Edző részben érintsd meg az Edző kiválasztása vagy Edző váltása gombot az edző-választó megnyitásához." },
        { label: "Értesítések engedélyezése", desc: "Az Értesítések kártya mutatja az aktuális engedélyszintedet. Ha az értesítések ki vannak kapcsolva, érintsd meg az Engedélyezés gombot a napi bejelentkezési emlékeztetők bekapcsolásához. Ha aznap még nem naplóztál, este 7-kor értesítést kapsz." },
        { label: "Kijelentkezés", desc: "A Kijelentkezés gomb az Én oldal alján található." },
      ] as Step[],
      note: { bold: "GL-pontok", text: " (IPF Goodlift-formula) automatikusan számítódnak az összteljesítményedből (guggolás + fekvenyomás + elhúzás jelenlegi rekordok) és testtömegből. Állítsd be a nemet, testtömeget és emeléseket a megtekintéshez." },
    },
    s08: {
      title: "Coach AI",
      subtitle: "Sportpszichológia AI · Az edződ módszertanára építve",
      steps: [
        { label: "Nyisd meg a Coach AI-t", desc: "Érintsd meg a csevegő buborék ikont az alsó navigációban. Ha először nyitod meg korábbi előzmény nélkül, személyre szabott prompt-chipek jelennek meg a legutóbbi naplóbejegyzéseid, a közelgő verseny és a már mappelt ego-state-ek alapján." },
        { label: "Mit kérdezhetsz", desc: "Legutóbbi naplóbejegyzések elemzése · Mentális felkészülés versenyekre · Nehéz edzések feldolgozása · Ego-state-ek feltérképezése · Vizualizációs vagy relaxációs szkriptek generálása · Pszichológiai állapotváltás · Önkétség vagy szorongás feldolgozása" },
        { label: "Szkriptek az edződ hangjában", desc: "Minden AI által generált szkript – vizualizáció, stabilizálás, verseny előtti rutin – lejátszható az edződ hangjában. Érintsd meg a ▶ Lejátszás gombot a szkript kártyán. Mentsd el a szkripteket a könyvtárba, hogy bármikor újra meghallgathasd." },
        { label: "Intelligens promptok", desc: "Ha a Coach AI-t írás nélkül nyitod meg, személyre szabott prompt-chipek jelennek meg. Ezek frissülnek a legutóbbi bejegyzéseid, közelgő verseny és ego-state-ek alapján. Érintsd meg egyiket a foglalkozás azonnali indításához." },
      ] as Step[],
      note: { text: "A Coach AI akkor működik a legjobban, amikor a naplód aktív. Minél többet írsz, annál több kontextusa van az AI-nak – és annál relevánsabbak lesznek a megfigyelései és javaslatai." },
    },
    s09: {
      title: "Ego-State-ek",
      subtitle: "Pszichológiai személyiségek · Tudatos állapottervezés",
      intro: "Az ego-state egy pszichológiai személyiség, amelyet tudatosan veszel fel egy adott kontextusra. Minden state-nek nyolc összetevője van:",
      table: [
        ["Név", "Hogyan nevezed ezt a részét magadnak – pl. A Gép, Az Építő"],
        ["Szín", "Egy vizuális horgony a gyors felismeréshez"],
        ["Testtartás", "Hogyan tartja magát a tested, amikor teljesen ebben az állapotban vagy"],
        ["Testérzet", "Hol érzed ezt az állapotot a testedben és hogyan hat"],
        ["Belső hang", "Az állapot belső hangjának tónusa, sebessége és stílusa"],
        ["Eredet", "Mikor született ez az állapot? Milyen helyzet hozta létre?"],
        ["Terület", "Milyen kontextusok hívják elő ezt az állapotot?"],
        ["Árnyékoldal", "Hogyan néz ki, ha ez az állapot rossz pillanatban jelenik meg?"],
        ["Aktiválási rituálé", "Három konkrét lépés, hogy szándékosan átválts ebbe az állapotba"],
      ] as [string, string][],
      steps: [
        { label: "Feltérképezés Coach AI-n keresztül", desc: "Kérdezd a Coach AI-t: 'Térképezd fel velem az ego-state-eimet.' Nyolc kérdést tesz fel egymás után, majd state-kártyát jelenít meg, amelyet egy érintéssel elmented." },
        { label: "Megtekintés az Én fülön", desc: "Mentés után egy Ego-State-ek rész jelenik meg az Én fülön. Érintsd meg az állapotok megtekintéséhez, szerkesztéséhez vagy újak hozzáadásához." },
        { label: "Váltás gyakorlása", desc: "A készség abban rejlik, hogy felismerd, melyik állapotot kívánja az adott pillanat, és belépj az aktiválási rituálén keresztül – mielőtt a pillanat megköveteli. A gondolkodó mód végrehajtás közben bénultságot okoz. A harcos mód regenerálódás közben kiégést okoz." },
      ] as Step[],
    },
    s10: {
      title: "Heti és havi bejelentkezések",
      subtitle: "Strukturált reflexió · Az edző láthatósága",
      steps: [
        { label: "Heti bejelentkezés", desc: "Minden hét végén megjelenik egy kérdés. Értékelj öt területet: általános hangulat, edzésminőség, energiaszint, alvásminőség és a következő hétre való felkészültség (mindegyik 1–10). Aztán add meg a legnagyobb sikered, fő kihívásodat és egy fókuszt a következő hétre. Kb. 60 másodpercet vesz igénybe." },
        { label: "Havi bejelentkezés", desc: "Minden hónap végén jelenik meg, ugyanazon öt értékeléssel, plusz három mélyebb kérdéssel: legnagyobb áttörés ebben a hónapban, legfontosabb önismereti tanulság és szándékod a következő hónapra." },
        { label: "Az edző láthatósága", desc: "Az edződ látja az összes bejelentkezési választ az irányítópultján. Ezek strukturált képet adnak arról, hogyan érzett minden hét és hónap – túl az egyes edzésnaplóbejegyzéseken." },
      ] as Step[],
      note: { text: "A bejelentkezések elkülönülnek a napi naplódtól és edzésnaplódtól. Ezek heti és havi pulzus – a napi bejegyzések felett álló nagyobb kép." },
    },
    ref: {
      title: "Gyors áttekintő",
      subtitle: "Mit csinál minden fül egy pillantásra",
      headers: ["Fül", "Mit csinál", "Mire használd"] as [string, string, string],
      rows: [
        ["Ma", "Napi bejelentkezés, fázis visszaszámlálás, emelési célok, tanfolyamkártya", "Minden nap – kezdj itt"],
        ["Napló", "Szabad szöveges bejegyzések, AI-hangulat és téma-jelölés", "Edzések, versenyek után vagy amikor valami foglalkoztat"],
        ["Eszközök", "Sportpszichológiai felmérések (SAT, ACSI, CSAI-2, DAS)", "A program elején és rendszeresen a haladás nyomon követésére"],
        ["Coach AI", "Sportpszichológia AI, szkript generálás, ego-state feltérképezés", "Verseny előtt, nehéz edzések után, amikor valamit fel kell dolgoznod"],
        ["Tanfolyam", "16 hetes strukturált mentális program", "Hetente – kövesd az aktuális heti tartalmat"],
        ["Én", "Profilszerkesztő, emelések, célok, edző, ego-state-ek, kijelentkezés", "Amikor az adataid változnak vagy egy új ego-state feltérképezése után"],
      ] as [string, string, string][],
    },
  },
} as const;

export type AthleteContent = typeof athleteContent.en;
