// AUTO-GENERATED from ÖIT_GOLD_v2.0_Eng.xlsx + Hannah English questionnaire (cleaned).
// Item text cleaning: "no"→"0" OCR corruption reversed; row-position indexing used
// to recover items Hannah mis-labeled; Q49 backfilled from Hungarian.

export const FACTOR_NAMES = [
  "Performance", "Affiliation", "Aggression", "Defensiveness", "Consciousness",
  "Dominance", "Exhibition", "Autonomy", "Caregiving", "Order", "Helplessness",
] as const;

export type FactorName = typeof FACTOR_NAMES[number];

export type Item = {
  id: number;           // 1..165
  factor: number;       // 0..10, index into FACTOR_NAMES
  key: 0 | 1;           // answer value that earns a point
  text: { en: string; hu: string };
};

export const ITEMS: Item[] = [
  { id: 1, factor: 0, key: 1, text: { en: "Do you seek accomplishing something big in life?", hu: "Szeretne véghezvinni valami igazán jelentőset?" } },
  { id: 2, factor: 1, key: 0, text: { en: "Are you able to stay away from your friends for a longer period of time?", hu: "Könnyen meg tud lenni a barátai nélkül huzamosabb ideig is?" } },
  { id: 3, factor: 2, key: 1, text: { en: "Do you get angry easily when things do not go your way?", hu: "Hamar dühös lesz, ha nem kapja meg, amit akar?" } },
  { id: 4, factor: 3, key: 1, text: { en: "Are you generally interested in what people think of you?", hu: "Mindig igyekszik pontosan megtudni, hogy mások hogyan vélekednek Önről?" } },
  { id: 5, factor: 4, key: 1, text: { en: "Do you sometimes feel a sense of guilt without knowing exactly why?", hu: "Szokott lelkiismeret-furdalást érezni anélkül is, hogy pontosan tudná az okát?" } },
  { id: 6, factor: 5, key: 1, text: { en: "Do your friends think that you would be suitable for a leadership position?", hu: "Barátai szerint Ön alkalmas (volna) vezetői állásra?" } },
  { id: 7, factor: 6, key: 1, text: { en: "Do you like to dress uniquely?", hu: "Szeret úgy öltözni, hogy különbözzön a többiektől?" } },
  { id: 8, factor: 7, key: 0, text: { en: "Do you like taking the advice of the elderly or people with more experience?", hu: "Szívesen követi idősebb, tapasztaltabb emberek tanácsait?" } },
  { id: 9, factor: 8, key: 1, text: { en: "Would you choose to work with children in your career?", hu: "Választaná-e hivatásául a gyermekekkel való foglalkozást?" } },
  { id: 10, factor: 9, key: 1, text: { en: "Are you annoyed by messy, inaccurate people?", hu: "Bosszantják a rendetlen, pontatlan emberek?" } },
  { id: 11, factor: 10, key: 1, text: { en: "In case of illness or suffering an accident, do you accept to be taken care of?", hu: "Ha beteg vagy baleset éri, szereti, ha törődnek Önnel?" } },
  { id: 12, factor: 0, key: 1, text: { en: "Do you find yourself dreaming about achieving great things?", hu: "Álmodozik-e néha arról, hogy egyszer nagy dolgokat fog véghezvinni?" } },
  { id: 13, factor: 1, key: 1, text: { en: "Do you feel depressed and sad when you have to part with your best friend?", hu: "Lehangolt és szomorú lesz, ha el kell válnia legjobb barátjától?" } },
  { id: 14, factor: 2, key: 1, text: { en: "Do you sometimes like to tease or trick people?", hu: "Szereti néha ingerelni vagy bolonddá tenni az embereket?" } },
  { id: 15, factor: 3, key: 1, text: { en: "Do you think it is harder for you to take criticism than it is for others?", hu: "Másoknál nehezebben viseli a kritikát?" } },
  { id: 16, factor: 4, key: 0, text: { en: "Are you able to do someone wrong without feeling particularly guilty?", hu: "Képes igazságtalan, helytelen dolgot is cselekedni különösebb bűntudat nélkül?" } },
  { id: 17, factor: 5, key: 0, text: { en: "Can you easily be persuaded to change your decisions, choices?", hu: "Könnyen rá tudják venni döntései, elhatározásai megváltoztatására?" } },
  { id: 18, factor: 6, key: 1, text: { en: "Do you consider a meeting where you remain unrecognized as a failure?", hu: "Sikertelennek érzi azt az összejövetelt, ahol nem figyeltek fel Önre?" } },
  { id: 19, factor: 7, key: 1, text: { en: "Can you remain independent and autonomous from the opinions of friends in your decision-making?", hu: "Komoly döntésekben független és önálló marad baráti véleményétől?" } },
  { id: 20, factor: 8, key: 1, text: { en: "Can you imagine spending most of your time and giving up comfort for supporting the young and weak?", hu: "El tudná képzelni, hogy idejének és kényelmének nagy részét a fiatalabbak, gyengébbek támogatására áldozza?" } },
  { id: 21, factor: 9, key: 0, text: { en: "Are you somewhat negligent in keeping your surroundings clean?", hu: "Kissé hanyag abban, hogy maga körül kifogástalan rendet, tisztaságot tartson?" } },
  { id: 22, factor: 10, key: 0, text: { en: "Do you avoid complaining when something unpleasant happens?", hu: "Kerüli-e a panaszkodást olyankor, ha valami kellemetlenség éri?" } },
  { id: 23, factor: 0, key: 1, text: { en: "Would you willingly accomplish tasks that others consider to require a lot of effort?", hu: "Szeretne-e olyasmit véghezvinni, ami mások szerint igen nagy erőfeszítést igényel?" } },
  { id: 24, factor: 1, key: 1, text: { en: "Is it very important to you to stay in touch with friends and relatives (e.g. through the phone) even when they are away?", hu: "Nagyon fontos, hogy barátaival, rokonaival távollétük alatt is kapcsolatban maradon (pl. telefonon)?" } },
  { id: 25, factor: 2, key: 1, text: { en: "Do you get angry easily with other people?", hu: "Könnyen haragszik meg más emberekre?" } },
  { id: 26, factor: 3, key: 1, text: { en: "Do you often think back to embarrassing situations that have happened to you in the past?", hu: "Gondolatban gyakran tér vissza az Önt ért kínos szituációkra?" } },
  { id: 27, factor: 4, key: 1, text: { en: "Do you strive for continuous improvement?", hu: "Törekszik arra, hogy folyamatosan fejlődjön?" } },
  { id: 28, factor: 5, key: 1, text: { en: "Are you more likely to have an impact on others than they have on you?", hu: "Gyakrabban befolyásol másokat, mint mások Önt?" } },
  { id: 29, factor: 6, key: 0, text: { en: "Do you feel uncomfortable when you get noticed?", hu: "Kellemetlenül érzi magát  ha felfigyelnek Önre?" } },
  { id: 30, factor: 7, key: 1, text: { en: "Do you often feel inclined to do things that go against the norm?", hu: "Gyakran érez kedvet olyasmit tenni, ami ellenkezik a szokásokkal?" } },
  { id: 31, factor: 8, key: 1, text: { en: "Are you likely to feel intense discomfort when someone vulnerable gets mocked or hurt?", hu: "Nagyon zavarja, ha mások védteleneket gúnyolnak vagy bántanak?" } },
  { id: 32, factor: 9, key: 1, text: { en: "Can you cope well with situations where you have to follow strict rules?", hu: "Jól tud érvényesülni olyan helyzetekben, ahol szigorú szabályok szerint kell viselkedni?" } },
  { id: 33, factor: 10, key: 0, text: { en: "Are you uncomfortable around people who are overly helpful and self-sacrificing?", hu: "Rosszul érzi magát túlzottan segítőkész és önfeláldozó emberek közelében?" } },
  { id: 34, factor: 0, key: 1, text: { en: "Is it important to succeed in everything you do?", hu: "Fontos, hogy minden sikerüljön, amibe belekezd?" } },
  { id: 35, factor: 1, key: 0, text: { en: "Does it take a somewhat long time for you to feel affection or attachment to a new acquaintance?", hu: "Hosszú időbe beletelik, amíg vonzódást, ragaszkodást érz egy új ismerős iránt?" } },
  { id: 36, factor: 2, key: 1, text: { en: "Do you sometimes react overly emotional when you are angry?", hu: "Megesik, hogy mérgében kikel magából?" } },
  { id: 37, factor: 3, key: 1, text: { en: "When criticised, do you always try to defend yourself?", hu: "Ha kritizálják, mindig igyekszik védeni magát?" } },
  { id: 38, factor: 4, key: 1, text: { en: "Do you ever regret your actions after doing them?", hu: "Megesik, hogy utólag megbánja a tetteit?" } },
  { id: 39, factor: 5, key: 1, text: { en: "Do you often lead conversations in a group of friends?", hu: "Baráti társaságban rendszerint Ön a hangadó?" } },
  { id: 40, factor: 6, key: 0, text: { en: "Do you feel embarrassed when people comment on your appearance or clothing?", hu: "Zavarba hozza, ha észrevételeket tesznek külsejére, ruhájára?" } },
  { id: 41, factor: 7, key: 1, text: { en: "Do you easily become defiant or stubborn when others try to control you?", hu: "Könnyen válik dacossá, makaccsá, ha mások irányítani próbálják?" } },
  { id: 42, factor: 8, key: 1, text: { en: "Would it give you comfort to entirely devote yourself to charity?", hu: "Kielégítené, ha teljes egészében a jótékonykodásnak szentelné magát?" } },
  { id: 43, factor: 9, key: 0, text: { en: "Would you consider planning all of your tasks beforehand to be boring?", hu: "Unalmas volna minden munkát előre, minden részletében megtervezni és megszervezni?" } },
  { id: 44, factor: 10, key: 1, text: { en: "Do you often need to be taken care of?", hu: "Gyakran igényli, hogy törődjenek Önnel?" } },
  { id: 45, factor: 0, key: 1, text: { en: "Is it important for you to be the best at your job?", hu: "Fontos Önnek, hogy a munkáját másoknál jobban tudja elvégezni?" } },
  { id: 46, factor: 1, key: 0, text: { en: "Would it be nice to get away from relatives and friends for a little while?", hu: "Jó volna időnként egy időre távol lenni a rokonoktól, barátoktól?" } },
  { id: 47, factor: 2, key: 1, text: { en: "Do you enjoy making your opponents look ridiculous?", hu: "Szórakoztatja, ha nevetségessé tudja tenni ellenfeleit?" } },
  { id: 48, factor: 3, key: 1, text: { en: "Do you avoid certain opportunities because of the fear of failure?", hu: "Sokszor azért kerül bizonyos dolgokat, mert fél, hogy kudarcot vallana velük?" } },
  { id: 49, factor: 4, key: 1, text: { en: "Do you feel guilty even over small things?", hu: "Apróbb dolgok miatt is képes bűntudatot érezni?" } },
  { id: 50, factor: 5, key: 1, text: { en: "Do you think you would do well in a profession with influence, power, control over others?", hu: "Jól boldogul(na) olyan hivatásban, ahol befolyása, hatalma, irányítási joga van (volna) mások felett?" } },
  { id: 51, factor: 6, key: 0, text: { en: "Would you choose a job where you would often be required to appear in public, speak or perform in front of others?", hu: "Rossz választás (volna) az olyan foglalkozás, ahol gyakran kell(ene)  mások előtt nyilvánosan fellépni, beszélni, szerepelni?" } },
  { id: 52, factor: 7, key: 1, text: { en: "Is being independent important to you, so that you can always choose freely?", hu: "Fontos Önnek a függetlenség, hogy mindig a maga útját járhassa?" } },
  { id: 53, factor: 8, key: 1, text: { en: "Are you always willing to lend your belongings to people who need them?", hu: "Mindig hajlandó a holmijait kölcsönadni, oda adni azoknak, akiknek szükségük van rá?" } },
  { id: 54, factor: 9, key: 0, text: { en: "Do you usually find it difficult to manage your time well?", hu: "Általában nehezére esik jól beosztani az idejét?" } },
  { id: 55, factor: 10, key: 1, text: { en: "Do you very much demand affection and tenderness from others?", hu: "Nagyon igényli a gyengédséget, a ragaszkodás jeleit mások részéről?" } },
  { id: 56, factor: 0, key: 1, text: { en: "Do you always set high standards in order to be the most productive?", hu: "Mindig magasra helyezi a mércét azért, hogy ezzel minél többet produkáljon?" } },
  { id: 57, factor: 1, key: 1, text: { en: "If it were possible, would you keep your friends and acquaintances around you all the time?", hu: "Ha lehetséges volna akkor, barátait, ismerőseit folyton maga körül tartaná?" } },
  { id: 58, factor: 2, key: 0, text: { en: "Is it difficult to irritate or annoy you?", hu: "Nehéz ingerelni, felbosszantani?" } },
  { id: 59, factor: 3, key: 1, text: { en: "If something doesn't work, do you always look for excuses and explanations?", hu: "Ha valami nem sikerül, mindig keresi a mentséget, a magyarázatot?" } },
  { id: 60, factor: 4, key: 1, text: { en: "Are you uncomfortable making statements about others without being able to remain completely objective?", hu: "Kényelmetlen, ha másokról úgy kell nyilatkoznia, hogy nem tud teljesen tárgyilagos maradni?" } },
  { id: 61, factor: 5, key: 0, text: { en: "Do you find it difficult to defend your rights in front of people on whom you are dependent?", hu: "Nehezére esik megvédeni a jogait olyanok előtt, akiktől függő viszonyban van?" } },
  { id: 62, factor: 6, key: 0, text: { en: "Do you like to live your life in a way that attracts as little attention as possible?", hu: "Szeret úgy élni, hogy a lehető legkevésbé keltse fel mások figyelmét?" } },
  { id: 63, factor: 7, key: 1, text: { en: "Do you care little for the opinions of others?", hu: "Keveset ad mások véleményére?" } },
  { id: 64, factor: 8, key: 1, text: { en: "Do you enjoy raising and taking care of dogs, cats and other animals?", hu: "Szívesen nevel, gondoz kutyát, macskát és más állatokat?" } },
  { id: 65, factor: 9, key: 1, text: { en: "Do you dislike people who sometimes violate the rules of cleanliness and hygiene?", hu: "Nagyon ellenszenvesek Önnek azok, akik időnként vétenek a tisztaság, a  higiénia rendszabályai ellen?" } },
  { id: 66, factor: 10, key: 1, text: { en: "Do you quickly feel abandoned and helpless in strange places?", hu: "Idegen helyen hamar elhagyatottnak, kiszolgáltatottnak érzi magát?" } },
  { id: 67, factor: 0, key: 1, text: { en: "Are you prepared to go to great lengths to get ahead in life?", hu: "Készen áll nagyon sok fáradságot áldozni azért, hogy előbbre jusson az életben?" } },
  { id: 68, factor: 1, key: 1, text: { en: "Is loyalty and perseverance to friends important to you?", hu: "Önnek fontos a barátok iránti hűség és kitartás?" } },
  { id: 69, factor: 2, key: 1, text: { en: "Would you protest loudly if someone in line pushed in front of you?", hu: "Hangosan tiltakozna, ha valaki a sorban Ön elé tolakodna?" } },
  { id: 70, factor: 3, key: 0, text: { en: "Are you able to maintain your self-confidence in the presence of superior, confident people?", hu: "Képes  megőrizni az önbizalmát fölényes, magabiztos emberek között is?" } },
  { id: 71, factor: 4, key: 1, text: { en: "Do you refrain from certain actions because you are not sure that you would do the right thing?", hu: "Tartózkodik-e bizonyos dolgoktól csak azért, mert nem biztos benne, hogy helyesen és igazságosan fog cselekedni?" } },
  { id: 72, factor: 5, key: 0, text: { en: "Have you ever been harmed by not being able to defend your interests?", hu: "Származott már kára abból, hogy nem tudta az érdekeit megvédeni?" } },
  { id: 73, factor: 6, key: 1, text: { en: "Do you sometimes goof around to entertain others?", hu: "Szokott néha a társaság kedvéért mókázni, bolondozni, bohóckodni?" } },
  { id: 74, factor: 7, key: 1, text: { en: "Is the freedom of deciding where and when to go important to you?", hu: "Fontos-e a kötetlenség, hogy akkor és oda mehessen, ahová kedve tartja?" } },
  { id: 75, factor: 8, key: 0, text: { en: "Do you consciously avoid people who are likely to ask for your help and support?", hu: "Igyekszik kerülni azokat, akik várhatóan később a segítségét, támogatását fogják kérni?" } },
  { id: 76, factor: 9, key: 0, text: { en: "Are you a stranger to precision and paying meticulous attention to details?", hu: "Idegen Öntől a precizitás, az aprólékos pontosságot igénylő elfoglaltság?" } },
  { id: 77, factor: 10, key: 1, text: { en: "Do you always get homesick easily when abroad or in another city?", hu: "Mindig könnyen elfogja külföldön vagy más városban a honvágy?" } },
  { id: 78, factor: 0, key: 1, text: { en: "Is it true that competition is the most important driving force for human progress?", hu: "Igaz-e, hogy a versengés az emberi haladás legfontosabb hajtóereje?" } },
  { id: 79, factor: 1, key: 0, text: { en: "Does it matter to you whether you make new friends?", hu: "Számít Önnek, hogy sikerül-e új barátokat szereznie?" } },
  { id: 80, factor: 2, key: 1, text: { en: "Do you like to challenge opinions that are not your own?", hu: "Szívesen szembeszáll az önével ellenkező véleményekkel?" } },
  { id: 81, factor: 3, key: 1, text: { en: "Are you always careful to avoid situations where you might be ridiculed?", hu: "Mindig gondosan kerüli az olyan helyzeteket, ahol nevetségessé válhat?" } },
  { id: 82, factor: 4, key: 1, text: { en: "Have you ever been disappointed in yourself because you failed to be absolutely fair and honest?", hu: "Csalódott-e valaha önmagában, amiért nem tudtott abszolút igazságos és becsületes lenni?" } },
  { id: 83, factor: 5, key: 0, text: { en: "Do you find it difficult to express your own opinions in a debate?", hu: "Nehezére esik vitában a saját véleményét kifejteni?" } },
  { id: 84, factor: 6, key: 1, text: { en: "When telling a story, do you sometimes add untrue details to make it more engaging?", hu: "Ha történetet mesél, szokta „színezni” egy is színészkedéssel?" } },
  { id: 85, factor: 7, key: 0, text: { en: "Do you find it difficult to give your best performance in a subordinate position?", hu: "Nehéz alárendelt pozícióban maximális teljesítményt nyújtania?" } },
  { id: 86, factor: 8, key: 0, text: { en: "Are you unable to show empathy and compassion towards people who are in conflict with society (alcoholics, homeless, etc.)?", hu: "Képtelen megértést, együttérzést tanúsítani olyan emberek felé, akik összeütközésbe kerültek a társadalommal (alkoholisták, hajléktalanok stb.)?" } },
  { id: 87, factor: 9, key: 0, text: { en: "Is it boring and bad to have a strict daily schedule for work, rest and meals?", hu: "Unalmas és rossz, ha a napi munka, pihenés, étkezés ideje pontosan beosztott?" } },
  { id: 88, factor: 10, key: 0, text: { en: "Is it a burden if you are constantly being shown affection and devotion to?", hu: "Terhére van, ha folyton gyengédséget, odaadást mutatnak Ön iránt?" } },
  { id: 89, factor: 0, key: 1, text: { en: "Is it necessary for your self-confidence to feel that you have succeeded in difficult tasks?", hu: "Szükséges az önbizalmához, hogy érezze, sikerrel oldott meg nehéz feladatokat?" } },
  { id: 90, factor: 1, key: 1, text: { en: "Do you expect loyalty and devotion from your friends and acquaintances?", hu: "Megköveteli a bajtársiasságot és az odaadást a barátaitól, ismerőseitől?" } },
  { id: 91, factor: 2, key: 0, text: { en: "Do you try to avoid showing your emotions when you are upset or angry?", hu: "Igyekszik kerülni érzelmei kimutatását, amikor izgatott, haragos?" } },
  { id: 92, factor: 3, key: 0, text: { en: "Are you able to talk without anxiety about a subject you are not comfortable with?", hu: "Képes szorongás nélkül beszélni olyan témáról is, amelyben nem igazán otthonos?" } },
  { id: 93, factor: 4, key: 1, text: { en: "Do you tend to be more strict than others about what is right and wrong?", hu: "Általában másoknál szigorúbban ítéli meg, mi helyes és mi helytelen?" } },
  { id: 94, factor: 5, key: 1, text: { en: "When meeting new people, do you usually lead the conversation?", hu: "Új emberekkel ismerkedve általában Ön vezeti a beszélgetést?" } },
  { id: 95, factor: 6, key: 1, text: { en: "Are you often said to have a sense of humour?", hu: "Gyakran mondják Önre, hogy van humora?" } },
  { id: 96, factor: 7, key: 0, text: { en: "Are you happy to take on tasks that involve commitment and responsibility?", hu: "Szívesen vállal kötöttséggel, felelősséggel járó feladatokat?" } },
  { id: 97, factor: 8, key: 1, text: { en: "Do you try to do small favours for people you know at every opportunity?", hu: "Igyekszik minden kínálkozó alkalommal apró szívességeket tenni ismerőseinek?" } },
  { id: 98, factor: 9, key: 0, text: { en: "Are you able to work calmly in chaos and disorder?", hu: "Képes  felfordulás, rendetlenség ellenére is nyugodtan dolgozni?" } },
  { id: 99, factor: 10, key: 1, text: { en: "Do you often feel that people do not pay enough attention to you?", hu: "Gyakran érzi, hogy az emberek nem figyelnek eléggé Önre?" } },
  { id: 100, factor: 0, key: 1, text: { en: "Do you think most people are not goal-oriented and ambitious enough?", hu: "Úgy gondolja, az emberek többsége nem eléggé céltudatos és ambiciózus?" } },
  { id: 101, factor: 1, key: 1, text: { en: "Would you like to belong to a group where members show warmth, openness and friendliness towards each other?", hu: "Szívesen tartozna olyan csoporthoz, ahol a tagok meleg, szívélyes, baráti érzéseket mutatnak egymás iránt?" } },
  { id: 102, factor: 2, key: 1, text: { en: "Do you feel a will for revenge when someone offends you?", hu: "Érez bosszúvágyat, ha valaki megsérti?" } },
  { id: 103, factor: 3, key: 1, text: { en: "Do you feel embarrassed when you are forced into a situation where you have to defend your rights and point of view?", hu: "Zavarba jön, ha arra kényszerül, hogy a jogait védje?" } },
  { id: 104, factor: 4, key: 0, text: { en: "Can you lie out of necessity without remorse?", hu: "Képes szükségből lelkiismeretfurdalás nélkül hazudni?" } },
  { id: 105, factor: 5, key: 0, text: { en: "Do you usually feel too insignificant to express your opinion?", hu: "Rendszerint túl jelentéktelennek érzi magát ahhoz, hogy véleményét kinyilvánítsa?" } },
  { id: 106, factor: 6, key: 0, text: { en: "Would you be embarrassed to be noticed by the media?", hu: "Kínos volna, ha felfigyelne Önre a média?" } },
  { id: 107, factor: 7, key: 0, text: { en: "Do you feel that your views are generally aligning with the public?", hu: "Úgy érzi, nézetei általában megegyeznek a többi emberével?" } },
  { id: 108, factor: 8, key: 1, text: { en: "Are you very careful about not hurting the feelings of people weaker than you?", hu: "Nagyon vigyáz arra, hogy soha ne sértse meg az Önnél gyengébbek érzéseit?" } },
  { id: 109, factor: 9, key: 1, text: { en: "Is it important that you always dress impeccably?", hu: "Fontos, hogy mindig kifogástalan legyen az öltözéke?" } },
  { id: 110, factor: 10, key: 1, text: { en: "Is it easier to receive bad news in the presence of a good friend?", hu: "Könnyebb a rossz híreket egy jó barát jelenlétében fogadni?" } },
  { id: 111, factor: 0, key: 1, text: { en: "When starting something new, do you always try to do your best?", hu: "Ha egyszer belefogott valamibe, mindenképpen igyekszik a maximumot nyújtani?" } },
  { id: 112, factor: 1, key: 1, text: { en: "Are you willing to make financial sacrifices for your friends and relatives?", hu: "Szívesen hoz akár pénzügyi áldozatokat is a barátaiért, rokonaiért?" } },
  { id: 113, factor: 2, key: 1, text: { en: "Do you sometimes have hatred towards those who annoy you?", hu: "Olykor kifejezett gyűlöletet érez azok iránt, akik felbosszantják?" } },
  { id: 114, factor: 3, key: 1, text: { en: "Do you always take great care to behave well?", hu: "Mindig nagyon ügyel arra, hogy viselkedése mindig kifogástalan legyen?" } },
  { id: 115, factor: 4, key: 1, text: { en: "Do you feel embarrassed when you act against socially acceptable standards?", hu: "Kínosan érzi magát, ha olyasmihez támad kedve, ami ellenkezik a társadalmilag elfogadott viselkedéssel?" } },
  { id: 116, factor: 5, key: 1, text: { en: "Is it important to defend your own views in a debate if they conflict with those of others?", hu: "Fontos, hogy vitában megvédje saját nézeteit, ha azok ellenkeznek a másokéival?" } },
  { id: 117, factor: 6, key: 1, text: { en: "Do you like to be the centre of a group of people?", hu: "Szeret a társaság középpontja lenni?" } },
  { id: 118, factor: 7, key: 0, text: { en: "Do you get on easily and well with your superiors?", hu: "Könnyen és jól kijön a feletteseivel?" } },
  { id: 119, factor: 8, key: 0, text: { en: "Are you uncomfortable in situations where you have to care for or help others?", hu: "Kellemetlen az olyan helyzet, ahol kénytelen másokkal törődni, másokon segíteni?" } },
  { id: 120, factor: 9, key: 1, text: { en: "Is it important that your things are neat and tidy on your desk?", hu: "Fontos, hogy a dolgai rendben és szépen álljanak az asztalon?" } },
  { id: 121, factor: 10, key: 0, text: { en: "Do you hate the feeling of being pitied when you are ill?", hu: "Utálja, ha sajnálják, amikor beteg?" } },
  { id: 122, factor: 0, key: 1, text: { en: "Do you like jobs where you have to compete with others?", hu: "Kedveli az olyan munkákat, ahol másokkal versenyezni, vetélkedni kell?" } },
  { id: 123, factor: 1, key: 1, text: { en: "When you experience extreme emotions — either great happiness or deep sadness — is it important to share your feelings with someone?", hu: "Ha igazán boldog vagy igazán szomorú, akkor fontos, hogy valakivel megoszthassa az érzéseit?" } },
  { id: 124, factor: 2, key: 1, text: { en: "If you are verbally attacked by someone, do you prefer to say something back immediately?", hu: "Ha szavakban támadják, legszívesebben azonnal visszavág?" } },
  { id: 125, factor: 3, key: 0, text: { en: "Are you able to endure humiliation and to have your self-esteem permanently damaged?", hu: "Képes elviselni a megaláztatást, hogy az önbecsülése ettől maradandó csorbát szenvedjen?" } },
  { id: 126, factor: 4, key: 1, text: { en: "Do you generally feel more responsible and dutiful than others?", hu: "Általában felelősségteljesebbnek, kötelességtudóbbnek érzi magát másoknál?" } },
  { id: 127, factor: 5, key: 0, text: { en: "Do you often let others take the initiative?", hu: "Gyakran átengedi másoknak a kezdeményezést?" } },
  { id: 128, factor: 6, key: 0, text: { en: "Do you prefer to dress in a way that does not attract attention?", hu: "Szívesebben öltözik úgy, hogy ne keltsen feltűnést?" } },
  { id: 129, factor: 7, key: 1, text: { en: "Do you like to say what you think without being shy?", hu: "Szereti kimondani kertelés nélkül, amit gondol?" } },
  { id: 130, factor: 8, key: 0, text: { en: "Do you find doing a job where you have to care for the elderly or the sick to be difficult?", hu: "Rosszul boldogul(na) olyan hivatásban, ahol időseket vagy betegeket kell(ene)  ápolni, gondozni?" } },
  { id: 131, factor: 9, key: 1, text: { en: "Would you like to live your life in a way that everything runs smoothly and according to plan, without unexpected changes?", hu: "Jó volna úgy élni, hogy minden gördülékenyen és tervszerűen, váratlan változások nélkül történjen?" } },
  { id: 132, factor: 10, key: 1, text: { en: "Do you need encouragement after failing?", hu: "Ha valamiben kudarcot vallott, nagy szüksége van a biztatásra, bátorításra?" } },
  { id: 133, factor: 0, key: 1, text: { en: "Would you like to be outstanding in e.g. sport, arts, science?", hu: "Szívesen lenne kiemelkedő személy pl. sportban, művészetben, tudományban?" } },
  { id: 134, factor: 1, key: 1, text: { en: "Do you always try to establish a close and personal relationship with others?", hu: "Igyekszik mindig közeli és személyes kapcsolatot teremteni minden emberrel?" } },
  { id: 135, factor: 2, key: 1, text: { en: "Do you sometimes get so angry that you want to break something?", hu: "Néha annyira dühbe gurul, hogy legszívesebben összetör(ne) valamit?" } },
  { id: 136, factor: 3, key: 0, text: { en: "Are you able to remain calm when criticised or blamed?", hu: "Képes higgadt, nyugodt maradni, amikor kritizálják, hibáztatják?" } },
  { id: 137, factor: 4, key: 0, text: { en: "Can you renounce your principles and interests for the sake of justice?", hu: "Az igazságosság kedvéért le tud mondani az elveiről, az érdekeiről?" } },
  { id: 138, factor: 5, key: 0, text: { en: "As a leader (or if you were a leader), do you find it difficult to maintain order and discipline?", hu: "Vezetőként (/ha vezető volna) nehezére esik rendet, fegyelmet tartani?" } },
  { id: 139, factor: 6, key: 1, text: { en: "Do you say things that surprise or shock people?", hu: "Szokott olyasmit mondani, ami meglepi, vagy megdöbbenti az embereket?" } },
  { id: 140, factor: 7, key: 1, text: { en: "Is it better to work alone than with others?", hu: "Jobb egyedül dolgozni, mint másokkal együtt?" } },
  { id: 141, factor: 8, key: 1, text: { en: "Are you always willing to take the time and patience for those who ask for your help?", hu: "Mindig kész időt szentelni és venni a fáradságot azokért, akik a segítségét kérik?" } },
  { id: 142, factor: 9, key: 0, text: { en: "Would you be happy to work casual hours?", hu: "Szívesen dolgozna kötetlen munkaidőben?" } },
  { id: 143, factor: 10, key: 0, text: { en: "If you are in trouble, do you feel that the participation and understanding of others are unnecessary?", hu: "Ha bajban van, feleslegesnek érzi mások részvételét, megértését?" } },
  { id: 144, factor: 0, key: 1, text: { en: "Do you like to solve tasks that others have already found difficult to solve?", hu: "Szeret megoldani olyan feladatokat, amelyek másoknak már nehézséget okoztak?" } },
  { id: 145, factor: 1, key: 1, text: { en: "Do you get pleasure from taking care of things for people you know?", hu: "Örömet okoz Önnek, ha ismerősei számára el tud intézni dolgokat?" } },
  { id: 146, factor: 2, key: 1, text: { en: "If you are hurt, do you struggle controlling your anger and temper?", hu: "Ha megsértik, küzdenie kell, hogy uralkodni tudjon haragján, indulatain?" } },
  { id: 147, factor: 3, key: 1, text: { en: "Are your decisions often influenced by the thought that others will criticise you?", hu: "Döntéseit gyakran befolyásolja a gondolat, hogy mások kritizálni fogják?" } },
  { id: 148, factor: 4, key: 1, text: { en: "Do you often think about whether you did the right thing?", hu: "Sokat töpreng  utólag tettei helyességén?" } },
  { id: 149, factor: 5, key: 0, text: { en: "Are you opposed to situations where you have to direct the work of others?", hu: "Ellenére van az olyan helyzet, ahol mások munkáját kell irányítania?" } },
  { id: 150, factor: 6, key: 1, text: { en: "Do you like to speak in a way that makes others think you are imaginative and creative?", hu: "Szeret úgy beszélni, hogy mások ezért ötletesnek, kreatívnak tartsák?" } },
  { id: 151, factor: 7, key: 0, text: { en: "Is it true that \"he who thinks only for himself and does not care what others think will sooner or later be ruined\"?", hu: "Igaz-e, hogy: \"aki csak a maga feje után megy, és nem törődik mások véleményével, az előbb-utóbb pórul jár\" ?" } },
  { id: 152, factor: 8, key: 0, text: { en: "Do you prefer to avoid people in trouble?", hu: "Legszívesebben elkerüli a bajba jutott embereket?" } },
  { id: 153, factor: 9, key: 1, text: { en: "Do you like everything to have its place?", hu: "Szereti, ha mindennek megvan a helye?" } },
  { id: 154, factor: 10, key: 0, text: { en: "Do you strongly dislike telling friends about your difficulties and failures?", hu: "Utál barátnainak a nehézségeiről, kudarcairól beszámolni?" } },
  { id: 155, factor: 0, key: 1, text: { en: "Do you like setting goals and challenging yourself to prove your abilities?", hu: "Szívesen állít önmaga elé nehezen elérhető célokat csak azért, hogy bizonyítsa a képességeit?" } },
  { id: 156, factor: 1, key: 0, text: { en: "Do you prefer going on holiday alone, or with your partner, rather than with friends?", hu: "Jobban kedvel egyedül, vagy legfeljebb partnerével kettesben nyaralni, mint baráti társasággal?" } },
  { id: 157, factor: 2, key: 1, text: { en: "Do you sometimes say frivolous things just because you find it amusing to tease or annoy people?", hu: "Mond-e néha komolytalan dolgokat csak azért, mert mulatságosnak tartja az embereket ugratni, bosszantani?" } },
  { id: 158, factor: 3, key: 1, text: { en: "Does your self-esteem and self-respect depend to a large extent on the perception of others?", hu: "Önérzete, önbecsülése nagy mértékben függ mások megítélésétől?" } },
  { id: 159, factor: 4, key: 0, text: { en: "Would you sometimes like to be less conscientious?", hu: "Szeretne-e olykor kevésbé lelkiismeretes lenni?" } },
  { id: 160, factor: 5, key: 0, text: { en: "Do you usually avoid being put in a position of control?", hu: "Általában kitér az elől, hogy Ön kerüljön irányító pozícióba?" } },
  { id: 161, factor: 6, key: 0, text: { en: "Do you find it difficult to talk honestly about yourself in front of others?", hu: "Nehezére esik mások előtt önmagáról őszintén beszélni?" } },
  { id: 162, factor: 7, key: 1, text: { en: "Do you sometimes feel a desire to leave everything behind and start a completely new life as a free, independent person?", hu: "Érez időnként vágyat arra, hogy mindent otthagyjon, és szabad, független emberként teljesen új életet kezdjen?" } },
  { id: 163, factor: 8, key: 1, text: { en: "Do you get pleasure from helping a person in trouble?", hu: "Örömet szerez, ha segíteni tud egy bajba jutott emberen?" } },
  { id: 164, factor: 9, key: 0, text: { en: "When going on a trip, do you rely on the spontaneity of the situation rather than on a detailed itinerary?", hu: "Ha kirándulni megy, inkább bízza magát a helyzet spontán alakulására, mint előre kidolgozott részletes útitervre?" } },
  { id: 165, factor: 10, key: 1, text: { en: "Do you enjoy being helped and cared for by an older partner?", hu: "Kedvére van, ha egy idősebb társ segíti, gondoskodik Önről?" } },
];
