// Narrative interpretations for the CSAI-2 (Competitive State Anxiety Inventory-2).
// 3 subscales x 3 bands x 3 languages (en, hu, de).
// Tone: direct, practical sport-psychology voice for competitive strength/combat athletes.
// Important: CSAI-2 is a STATE measure -- results reflect how the athlete feels
// right now, before this specific competition, not a permanent trait.

import type { CsaiSubscaleKey, Band } from "./scoring";

// ---------------------------------------------------------------------------
// Shared types
// ---------------------------------------------------------------------------

export type LocalizedParagraphs = { en: string[]; hu: string[]; de: string[] };

export type SubscaleInterpretation = {
  name: { en: string; hu: string; de: string };
  definition: { en: string; hu: string; de: string };
  bands: Record<Band, LocalizedParagraphs>;
};

// ---------------------------------------------------------------------------
// General intro
// ---------------------------------------------------------------------------

export const CSAI_INTRO: LocalizedParagraphs = {
  en: [
    "The Competitive State Anxiety Inventory (CSAI-2) captures how you feel right now, in the lead-up to this specific competition. Unlike trait measures that describe your general personality, this is a snapshot -- a reading of your mental and physical state at this moment. The profile can look very different before your next event depending on the stakes, your preparation, and dozens of other situational factors. Treat these results as actionable real-time information, not as a permanent label.",
    "The inventory measures three distinct dimensions: cognitive anxiety (the mental worry and negative thoughts running through your mind), somatic anxiety (the physical arousal signals your body is sending -- heart rate, muscle tension, stomach butterflies), and self-confidence (your belief in your ability to perform well right now). Each dimension tells a different story, and the combination of all three paints the fullest picture of your competitive readiness.",
    "Use this profile to make immediate adjustments. High cognitive anxiety before a bout might call for a brief refocusing routine. Elevated somatic arousal might mean you need controlled breathing or a physical warm-up tweak. Low confidence can be addressed with targeted self-talk or reviewing your preparation log. The value of a state measure is that it points to what you can do right now, in the next few minutes, to optimise your performance state.",
  ],
  hu: [
    "A Verseny Alatti Szorongás Kérdőív (CSAI-2) azt ragadja meg, hogyan érzed magad éppen most, közvetlenül a verseny előtt. A vonásmérőktől eltérően, amelyek az általános személyiségedet írják le, ez egy pillanatkép -- a mentális és fizikai állapotod leolvasása ebben a pillanatban. A profilod egészen másképp nézhet ki a következő versenyed előtt, a téttől, a felkészültségedtől és számos más helyzeti tényezőtől függően. Kezeld ezeket az eredményeket azonnali, cselekvésre alkalmas információként, ne állandó címkeként.",
    "A kérdőív három különálló dimenziót mér: a kognitív szorongást (a fejedben kavargó aggodalmakat és negatív gondolatokat), a szomatikus szorongást (a tested által küldött fizikai arousal-jeleket -- szívverést, izomfeszültséget, gyomorgörcsöt), és az önbizalmat (a meggyőződésedet, hogy éppen most képes vagy jól teljesíteni). Minden dimenzió más történetet mesél, és a három együttese rajzolja meg a legteljesebb képet a versenyképességedről.",
    "Használd ezt a profilt azonnali módosításokra. A magas kognitív szorongás egy küzdelem előtt rövid újrafókuszáló rutint igényelhet. Az emelkedett szomatikus arousalt kontrollált légzés vagy az átformált bemelegítés kezelheti. Az alacsony önbizalmat célzott önbeszéddel vagy a felkészülési naplód áttekintésével lehet címezni. Egy állapotmérő értéke az, hogy rámutat, mit tehetsz most, a következő néhány percben, hogy optimalizáld a teljesítményállapotodat.",
  ],
  de: [
    "Das Competitive State Anxiety Inventory (CSAI-2) erfasst, wie du dich genau jetzt fühlst, in der Vorbereitung auf diesen spezifischen Wettkampf. Anders als Eigenschaftsmaße, die deine allgemeine Persönlichkeit beschreiben, ist dies eine Momentaufnahme -- eine Ablesung deines mentalen und körperlichen Zustands in diesem Augenblick. Das Profil kann vor deinem nächsten Wettkampf ganz anders aussehen, abhängig von der Bedeutung, deiner Vorbereitung und zahlreichen anderen situativen Faktoren. Behandle diese Ergebnisse als sofort verwertbare Echtzeitinformation, nicht als dauerhaftes Etikett.",
    "Das Inventar misst drei verschiedene Dimensionen: kognitive Angst (die mentalen Sorgen und negativen Gedanken, die durch deinen Kopf gehen), somatische Angst (die körperlichen Erregungssignale, die dein Körper sendet -- Herzfrequenz, Muskelspannung, Schmetterlinge im Bauch) und Selbstvertrauen (dein Glaube an deine Fähigkeit, gerade jetzt gut abzuschneiden). Jede Dimension erzählt eine andere Geschichte, und die Kombination aller drei zeichnet das vollständigste Bild deiner Wettkampfbereitschaft.",
    "Nutze dieses Profil für sofortige Anpassungen. Hohe kognitive Angst vor einem Kampf könnte eine kurze Refokussierungsroutine erfordern. Erhöhte somatische Erregung könnte bedeuten, dass du kontrollierte Atemtechniken oder eine Anpassung deines Aufwärmens brauchst. Niedriges Selbstvertrauen lässt sich mit gezieltem Selbstgespräch oder dem Durchgehen deines Vorbereitungsprotokolls angehen. Der Wert eines Zustandsmaßes ist, dass es aufzeigt, was du jetzt tun kannst, in den nächsten Minuten, um deinen Leistungszustand zu optimieren.",
  ],
};

// ---------------------------------------------------------------------------
// Subscale interpretations
// ---------------------------------------------------------------------------

export const SUBSCALE_INTERPRETATIONS: Record<CsaiSubscaleKey, SubscaleInterpretation> = {
  // =========================================================================
  // COGNITIVE ANXIETY
  // =========================================================================
  cognitive: {
    name: {
      en: "Cognitive Anxiety",
      hu: "Kognitív szorongás",
      de: "Kognitive Angst",
    },
    definition: {
      en: "The mental component of anxiety -- worrying thoughts, negative expectations, and concerns about performance, outcomes, or consequences. This is the voice in your head that questions whether you are ready.",
      hu: "A szorongás mentális komponense -- aggódó gondolatok, negatív elvárások, és a teljesítménnyel, eredményekkel vagy következményekkel kapcsolatos aggodalmak. Ez az a hang a fejedben, amely megkérdőjelezi, hogy kész vagy-e.",
      de: "Die mentale Komponente der Angst -- besorgte Gedanken, negative Erwartungen und Bedenken bezüglich Leistung, Ergebnis oder Konsequenzen. Das ist die Stimme in deinem Kopf, die infrage stellt, ob du bereit bist.",
    },
    bands: {
      low: {
        en: [
          "Your mind is quiet and clear heading into this competition. You are not caught up in worry about what might go wrong, how others will judge you, or whether your preparation is sufficient. This mental calmness means your cognitive resources are available for tactical thinking, reading your opponent, and executing your game plan rather than being consumed by self-doubt.",
          "Low cognitive anxiety before competition is a strong position to be in. It suggests you trust your preparation, feel aligned with your goals, and are not over-investing in outcome scenarios. Your attention is likely directed forward -- toward what you will do -- rather than inward toward what could go wrong. This is the kind of mental state that supports clean decision-making under pressure.",
          "Keep in mind that this is a snapshot of right now. The fact that your cognitive anxiety is low before this event does not guarantee it will stay low once competition begins. Have a brief refocusing cue ready -- a word, an image, a breath pattern -- in case worrying thoughts arise mid-performance. The athletes who sustain this clarity are the ones who have a plan for when it starts to slip.",
        ],
        hu: [
          "A fejed tiszta és nyugodt a verseny előtt. Nem ragadnak magukkal az aggodalmak arról, mi mehet rosszul, hogyan ítélnek meg mások, vagy elég volt-e a felkészülés. Ez a mentális nyugalom azt jelenti, hogy a kognitív erőforrásaid rendelkezésre állnak a taktikai gondolkodáshoz, az ellenfél olvasásához és a versenyterved végrehajtásához, ahelyett, hogy önkételkedés emésztené fel őket.",
          "Az alacsony kognitív szorongás verseny előtt erős pozíció. Arra utal, hogy bízol a felkészülésedben, összhangban érzed magad a céljaiddal, és nem fektetsz túl sokat az eredmény-forgatókönyvekbe. A figyelmed valószínűleg előre irányul -- arra, amit tenni fogsz --, nem pedig befelé, arra, ami rosszul sülhet el. Ez az a fajta mentális állapot, amely támogatja a tiszta döntéshozatalt nyomás alatt.",
          "Ne feledd, ez egy pillanatkép a jelenről. Az, hogy a kognitív szorongásod most alacsony, nem garantálja, hogy az is marad, amint a verseny elkezdődik. Legyen készen egy rövid újrafókuszáló jeled -- egy szó, egy kép, egy légzésminta -- arra az esetre, ha aggódó gondolatok merülnének fel teljesítmény közben. Azok a sportolók, akik fenntartják ezt a tisztaságot, azok, akiknek van tervük arra, amikor kezd elcsúszni.",
        ],
        de: [
          "Dein Kopf ist ruhig und klar vor diesem Wettkampf. Du bist nicht in Sorgen verstrickt darüber, was schiefgehen könnte, wie andere dich beurteilen oder ob deine Vorbereitung ausreichend war. Diese mentale Ruhe bedeutet, dass deine kognitiven Ressourcen für taktisches Denken, das Lesen deines Gegners und die Ausführung deines Wettkampfplans zur Verfügung stehen, anstatt von Selbstzweifeln aufgefressen zu werden.",
          "Niedrige kognitive Angst vor dem Wettkampf ist eine starke Ausgangsposition. Sie deutet darauf hin, dass du deiner Vorbereitung vertraust, dich mit deinen Zielen im Einklang fühlst und nicht zu viel in Ergebnisszenarien investierst. Deine Aufmerksamkeit ist wahrscheinlich nach vorne gerichtet -- auf das, was du tun wirst -- und nicht nach innen auf das, was schiefgehen könnte. Das ist die Art von mentalem Zustand, der saubere Entscheidungsfindung unter Druck unterstützt.",
          "Bedenke, dass dies eine Momentaufnahme von genau jetzt ist. Die Tatsache, dass deine kognitive Angst vor diesem Wettkampf niedrig ist, garantiert nicht, dass sie niedrig bleibt, sobald der Wettkampf beginnt. Halte ein kurzes Refokussierungssignal bereit -- ein Wort, ein Bild, ein Atemmuster -- für den Fall, dass sorgenvolle Gedanken während der Leistung auftreten. Die Athleten, die diese Klarheit aufrechterhalten, sind diejenigen, die einen Plan haben für den Moment, wenn sie zu schwinden beginnt.",
        ],
      },
      average: {
        en: [
          "You have a moderate level of mental concern about this competition -- some thoughts about how things might play out, some awareness of what is at stake. This is a normal and common pre-competition state. A degree of cognitive engagement with the upcoming challenge is not a problem; it reflects the fact that you care about the outcome and are mentally processing the situation.",
          "The key question is whether these thoughts are functional or disruptive. Functional worry looks like reviewing your game plan, anticipating scenarios, and mentally preparing responses. Disruptive worry looks like ruminating on failure, replaying past mistakes, or fixating on things outside your control. Pay attention to the content of your thoughts right now -- if they are mostly task-focused and forward-looking, your current state is serving you well.",
          "If you notice the worry tipping toward the disruptive end, you have time to intervene. A brief mindfulness exercise -- even 60 seconds of focused breathing -- can interrupt a negative thought loop. Alternatively, redirect your attention to your warm-up routine or a specific tactical element you want to execute. The goal is not to eliminate all thought about the competition, but to keep your thinking constructive and action-oriented. This reading reflects this moment only; it is not a verdict on your mental toughness.",
        ],
        hu: [
          "Mérsékelten foglalkoztatnak gondolatok erről a versenyről -- néhány gondolat arról, hogyan alakulhatnak a dolgok, némi tudatosság arról, mi forog kockán. Ez normális és gyakori verseny előtti állapot. A közelgő kihívással való bizonyos szintű kognitív foglalkozás nem probléma; azt tükrözi, hogy fontos számodra az eredmény, és mentálisan feldolgozod a helyzetet.",
          "A kulcskérdés az, hogy ezek a gondolatok funkcionálisak vagy zavaróak. A funkcionális aggodalom úgy néz ki, mint a versenyterved áttekintése, forgatókönyvek előrelátása és mentális válaszok felkészítése. A zavaró aggodalom úgy néz ki, mint a kudarcon való rumináció, múlt hibák újrajátszása vagy az irányításodon kívül eső dolgokra való fixálás. Figyelj a gondolataid tartalmára most -- ha többségük feladatközpontú és előre tekintő, a jelenlegi állapotod jól szolgál téged.",
          "Ha észreveszed, hogy az aggodalom a zavaró irányba billen, van időd beavatkozni. Egy rövid tudatossági gyakorlat -- akár 60 másodperc fókuszált légzés -- megszakíthat egy negatív gondolati hurkot. Alternatívaként irányítsd a figyelmedet a bemelegítési rutinodra vagy egy konkrét taktikai elemre, amelyet végre akarsz hajtani. A cél nem az, hogy minden gondolatot kiküszöbölj a versenyről, hanem hogy a gondolkodásod konstruktív és cselekvésorientált maradjon. Ez a leolvasás csak ezt a pillanatot tükrözi; nem ítélet a mentális erősségedről.",
        ],
        de: [
          "Du hast ein moderates Maß an mentaler Besorgnis bezüglich dieses Wettkampfs -- einige Gedanken darüber, wie die Dinge laufen könnten, ein gewisses Bewusstsein für das, was auf dem Spiel steht. Das ist ein normaler und häufiger Zustand vor dem Wettkampf. Ein gewisses Maß an kognitiver Auseinandersetzung mit der bevorstehenden Herausforderung ist kein Problem; es spiegelt die Tatsache wider, dass dir das Ergebnis wichtig ist und du die Situation mental verarbeitest.",
          "Die entscheidende Frage ist, ob diese Gedanken funktional oder störend sind. Funktionale Sorge sieht so aus wie das Durchgehen deines Wettkampfplans, das Vorwegnehmen von Szenarien und das mentale Vorbereiten von Reaktionen. Störende Sorge sieht so aus wie das Grübeln über Misserfolg, das Wiederholen vergangener Fehler oder das Fixieren auf Dinge außerhalb deiner Kontrolle. Achte auf den Inhalt deiner Gedanken gerade jetzt -- wenn sie größtenteils aufgabenbezogen und vorausschauend sind, dient dir dein aktueller Zustand gut.",
          "Wenn du bemerkst, dass die Sorge in die störende Richtung kippt, hast du noch Zeit einzugreifen. Eine kurze Achtsamkeitsübung -- selbst 60 Sekunden fokussiertes Atmen -- kann eine negative Gedankenschleife unterbrechen. Alternativ lenke deine Aufmerksamkeit auf deine Aufwärmroutine oder ein bestimmtes taktisches Element, das du ausführen möchtest. Das Ziel ist nicht, jeden Gedanken an den Wettkampf zu eliminieren, sondern dein Denken konstruktiv und handlungsorientiert zu halten. Dieses Ergebnis spiegelt nur diesen Moment wider; es ist kein Urteil über deine mentale Stärke.",
        ],
      },
      high: {
        en: [
          "Your mind is very active with worry and concern right now. You may be thinking about what will happen if you underperform, how others will react, whether your preparation was enough, or whether you can handle the pressure. This level of cognitive anxiety can interfere with performance -- not because the worry is irrational, but because it occupies mental bandwidth that you need for execution, timing, and tactical decision-making.",
          "This is important information, not an alarm. Many elite athletes experience high cognitive anxiety before significant competitions. The difference between those who perform well despite it and those who do not comes down to what they do with that anxiety in the next few minutes. You cannot think your way out of overthinking, but you can redirect your attention. Narrow your focus to a single, concrete task: your warm-up set, your opening sequence, the first technique you want to execute. Give your mind something productive to process instead of abstract worry.",
          "Consider whether specific concerns are driving this spike. Fear of disappointing others, concern about a specific opponent, doubts about a recent training block -- each has a different practical response. If you can identify the root, you can address it briefly and move on. If the worry is diffuse and generalised, a structured breathing exercise or a short conversation with your coach can bring you back to a task focus. Remember, this is a state reading, not a trait. Your next competition could look entirely different. Right now, the actionable step is to reclaim your attention from the worry and point it at the performance.",
        ],
        hu: [
          "A fejed most nagyon aktív aggodalmakkal és gondokkal. Lehet, hogy azon gondolkodsz, mi történik, ha alulteljesítesz, hogyan reagálnak mások, elég volt-e a felkészülés, vagy képes leszel-e kezelni a nyomást. A kognitív szorongás ilyen szintje befolyásolhatja a teljesítményt -- nem azért, mert az aggodalom irracionális, hanem mert elfoglalja azt a mentális sávszélességet, amelyre szükséged van a végrehajtáshoz, az időzítéshez és a taktikai döntéshozatalhoz.",
          "Ez fontos információ, nem riasztás. Sok élitsportoló tapasztal magas kognitív szorongást jelentős versenyek előtt. A különbség azok között, akik ennek ellenére jól teljesítenek, és azok között, akik nem, abban rejlik, hogy mit kezdenek ezzel a szorongással a következő néhány percben. Nem tudod kigondolni magad a túlgondolkozásból, de átirányíthatod a figyelmed. Szűkítsd a fókuszodat egyetlen konkrét feladatra: a bemelegítő sorozatodra, a nyitó szekvenciádra, az első technikára, amit végre akarsz hajtani. Adj az elmednek valami produktívat a feldolgozásra az absztrakt aggodalom helyett.",
          "Gondold át, vajon konkrét aggodalmak hajtják-e ezt a kiugró értéket. Félelem mások kiábrándulásától, aggodalom egy konkrét ellenfél miatt, kétségek egy közelmúltbeli edzésidőszak kapcsán -- mindegyiknek más gyakorlati válasza van. Ha azonosítani tudod a gyökeret, röviden kezelheted és továbblépehetsz. Ha az aggodalom diffúz és általánosított, egy strukturált légzőgyakorlat vagy egy rövid beszélgetés az edződdel visszahozhat a feladatfókuszba. Ne feledd, ez egy állapot-leolvasás, nem egy vonás. A következő versenyed teljesen másképp nézhet ki. Most az cselekvésre alkalmas lépés az, hogy visszaköveteled a figyelmedet az aggodalomtól és a teljesítményre irányítod.",
        ],
        de: [
          "Dein Kopf ist gerade sehr aktiv mit Sorgen und Bedenken. Vielleicht denkst du darüber nach, was passiert, wenn du unterdurchschnittlich abschneidest, wie andere reagieren werden, ob deine Vorbereitung ausreichend war oder ob du mit dem Druck umgehen kannst. Dieses Maß an kognitiver Angst kann die Leistung beeinträchtigen -- nicht weil die Sorge irrational ist, sondern weil sie mentale Bandbreite belegt, die du für Ausführung, Timing und taktische Entscheidungsfindung brauchst.",
          "Das ist eine wichtige Information, kein Alarm. Viele Spitzenathleten erleben hohe kognitive Angst vor bedeutenden Wettkämpfen. Der Unterschied zwischen denen, die trotzdem gut abschneiden, und denen, die es nicht tun, liegt daran, was sie mit dieser Angst in den nächsten Minuten anfangen. Du kannst dich nicht aus dem Überdenken herausdenken, aber du kannst deine Aufmerksamkeit umlenken. Verenge deinen Fokus auf eine einzige, konkrete Aufgabe: deinen Aufwärmsatz, deine Eröffnungssequenz, die erste Technik, die du ausführen willst. Gib deinem Geist etwas Produktives zum Verarbeiten statt abstrakter Sorge.",
          "Überlege, ob bestimmte Bedenken diesen Anstieg antreiben. Angst, andere zu enttäuschen, Sorge wegen eines bestimmten Gegners, Zweifel an einem kürzlichen Trainingsblock -- jedes hat eine andere praktische Antwort. Wenn du die Ursache identifizieren kannst, kannst du sie kurz ansprechen und weitermachen. Wenn die Sorge diffus und verallgemeinert ist, kann eine strukturierte Atemübung oder ein kurzes Gespräch mit deinem Trainer dich zurück zum Aufgabenfokus bringen. Denke daran, das ist eine Zustandsmessung, keine Eigenschaft. Dein nächster Wettkampf könnte völlig anders aussehen. Jetzt ist der handlungsfähige Schritt, deine Aufmerksamkeit von der Sorge zurückzufordern und sie auf die Leistung zu richten.",
        ],
      },
    },
  },

  // =========================================================================
  // SOMATIC ANXIETY
  // =========================================================================
  somatic: {
    name: {
      en: "Somatic Anxiety",
      hu: "Szomatikus szorongás",
      de: "Somatische Angst",
    },
    definition: {
      en: "The physical component of anxiety -- the body's arousal response. This includes heart rate changes, muscle tension, sweating, stomach sensations, and other physiological signs of activation. Some arousal is necessary for peak performance; the question is whether the level is optimal.",
      hu: "A szorongás fizikai komponense -- a test arousal-válasza. Ide tartoznak a szívfrekvencia-változások, izomfeszültség, izzadás, gyomortünetek és az aktiválás egyéb fiziológiai jelei. Bizonyos szintű arousal szükséges a csúcsteljesítményhez; a kérdés az, hogy az optimális szintű-e.",
      de: "Die körperliche Komponente der Angst -- die Erregungsreaktion des Körpers. Dazu gehören Herzfrequenzänderungen, Muskelspannung, Schwitzen, Magenempfindungen und andere physiologische Zeichen der Aktivierung. Ein gewisses Maß an Erregung ist für Spitzenleistung notwendig; die Frage ist, ob das Niveau optimal ist.",
    },
    bands: {
      low: {
        en: [
          "Your body is reporting very little physical arousal right now. Your heart rate feels normal, your muscles are relaxed, and you are not experiencing significant stomach tension or sweating. While this can simply reflect a calm, composed state, it is worth considering whether your activation level is high enough for what you are about to do. Competition demands a certain physiological readiness -- elevated heart rate, primed muscles, sharpened reflexes -- and starting too flat can mean slower reactions and less explosive output in the opening exchanges.",
          "In strength and combat sports specifically, under-arousal at competition time is a genuine concern. The athletes who perform best tend to arrive at the platform or the mat with their body already switched on -- not panicked, but activated. If you feel unusually relaxed or even lethargic, consider whether your warm-up has been intense enough, whether you have engaged with the competitive environment, or whether you might be emotionally checked out from the event.",
          "This does not mean you should manufacture panic. But a deliberate activation strategy -- a more aggressive warm-up, some high-tempo music, controlled breathing that emphasises the inhale, or brief intense visualisation -- can bring your body into a more competitive-ready state. Some athletes naturally ramp up once the competition starts, and if you know you are one of them, this low reading may simply reflect your personal rhythm. Know yourself, and adjust accordingly.",
        ],
        hu: [
          "A tested most nagyon alacsony fizikai arousalt jelez. A szívverésed normálisnak érződik, az izmaid lazák, és nem tapasztalsz jelentős gyomorfeszültséget vagy izzadást. Bár ez egyszerűen tükrözhet egy nyugodt, higgadt állapotot, érdemes megfontolni, hogy az aktivációs szinted elég magas-e ahhoz, amit tenni készülsz. A verseny bizonyos fiziológiai készültséget követel -- emelkedett szívfrekvenciát, felhúzott izmokat, élesített reflexeket --, és ha túl lapos állapotban indulsz, az lassabb reakciókat és kevésbé robbanékony teljesítményt jelenthet a nyitó cserékben.",
          "Különösen az erő- és küzdősportokban a versenyidőpont alatti alul-arousal valós aggodalom. Azok a sportolók, akik a legjobban teljesítenek, általában úgy érkeznek a dobogóra vagy a szőnyegre, hogy a testük már bekapcsolt -- nem pánikban, de aktiválva. Ha szokatlanul lazának vagy akár letargikusnak érzed magad, gondold át, hogy a bemelegítésed elég intenzív volt-e, hogy bekapcsolódtál-e a versenykörnyezetbe, vagy esetleg érzelmileg kiszálltál az eseményből.",
          "Ez nem azt jelenti, hogy pánikot kellene gyártanod. De egy tudatos aktivációs stratégia -- agresszívebb bemelegítés, gyors tempójú zene, a belégzést hangsúlyozó kontrollált légzés, vagy rövid intenzív vizualizáció -- versenyképes állapotba hozhatja a testedet. Néhány sportoló természetesen felpörgeti magát, amint a verseny elkezdődik, és ha tudod, hogy te ilyen vagy, ez az alacsony leolvasás egyszerűen a személyes ritmusodat tükrözheti. Ismerd önmagadat, és alkalmazkodj ennek megfelelően.",
        ],
        de: [
          "Dein Körper meldet gerade sehr wenig körperliche Erregung. Deine Herzfrequenz fühlt sich normal an, deine Muskeln sind entspannt, und du erlebst keine wesentliche Magenspannung oder Schwitzen. Während das einfach einen ruhigen, gefassten Zustand widerspiegeln kann, lohnt es sich zu überlegen, ob dein Aktivierungsniveau hoch genug ist für das, was du gleich tun wirst. Wettkampf erfordert eine gewisse physiologische Bereitschaft -- erhöhte Herzfrequenz, vorbereitete Muskeln, geschärfte Reflexe -- und zu flach zu starten kann langsamere Reaktionen und weniger explosive Leistung in den eröffnenden Austauschen bedeuten.",
          "Speziell im Kraft- und Kampfsport ist Untererregung zur Wettkampfzeit ein echtes Anliegen. Die Athleten, die am besten abschneiden, tendieren dazu, an der Plattform oder auf der Matte anzukommen, wobei ihr Körper bereits eingeschaltet ist -- nicht in Panik, aber aktiviert. Wenn du dich ungewöhnlich entspannt oder sogar lethargisch fühlst, überlege, ob dein Aufwärmen intensiv genug war, ob du dich mit der Wettkampfumgebung auseinandergesetzt hast, oder ob du emotional aus dem Event ausgecheckt sein könntest.",
          "Das bedeutet nicht, dass du künstlich Panik erzeugen solltest. Aber eine bewusste Aktivierungsstrategie -- ein aggressiveres Aufwärmen, Musik mit hohem Tempo, kontrolliertes Atmen mit Betonung der Einatmung oder kurze intensive Visualisierung -- kann deinen Körper in einen wettkampfbereiteren Zustand bringen. Manche Athleten steigern sich natürlich, sobald der Wettkampf beginnt, und wenn du weißt, dass du einer von ihnen bist, spiegelt dieser niedrige Wert möglicherweise einfach deinen persönlichen Rhythmus wider. Kenne dich selbst und passe entsprechend an.",
        ],
      },
      average: {
        en: [
          "Your body is showing a moderate level of physical activation -- some increased heart rate, perhaps some muscle tension or stomach awareness, but nothing overwhelming. This is often described as the zone of competitive readiness. Your sympathetic nervous system has engaged enough to sharpen your senses and prepare your muscles for explosive effort, without tipping into the kind of over-arousal that causes trembling hands, nausea, or rigid movement patterns.",
          "Moderate somatic arousal before competition is generally a positive sign. Research consistently shows that most athletes perform best at intermediate levels of physical activation -- enough adrenaline to be sharp, not so much that fine motor control deteriorates. In strength sports, this state supports the combination of maximal force production and precise technical execution that winning demands. In combat sports, it provides the alertness and reaction speed needed without the tunnel vision that excessive arousal can cause.",
          "Your main task right now is to maintain this state rather than either ramping up or calming down unnecessarily. Stay engaged with your warm-up routine, keep your movements purposeful, and avoid sitting still for too long (which can let arousal drop) or exposing yourself to excessive stimulation (which can spike it). Trust your body -- it is telling you it is ready. This state reading is specific to this moment, and managing it well in the next few minutes is what matters most.",
        ],
        hu: [
          "A tested mérsékelt fizikai aktiválást mutat -- némileg emelkedett szívfrekvencia, talán némi izomfeszültség vagy gyomortudatosság, de semmi túlzottan erős. Ezt gyakran a versenyképesség zónájaként írják le. A szimpatikus idegrendszered eleget kapcsolódott be ahhoz, hogy élesítse az érzékeidet és felkészítse az izmaidat a robbanékony erőfeszítésre, anélkül, hogy a túlzott arousal felé billenne, amely remegő kezeket, hányingert vagy merev mozgásmintákat okoz.",
          "A mérsékelt szomatikus arousal verseny előtt általában pozitív jel. A kutatások következetesen azt mutatják, hogy a legtöbb sportoló közepes szintű fizikai aktiválás mellett teljesít a legjobban -- elég adrenalin ahhoz, hogy éles legyen, de nem annyi, hogy a finommotorikus kontroll romlana. Az erősportokban ez az állapot támogatja a maximális erőtermelés és a precíz technikai végrehajtás kombinációját, amelyet a győzelem megkövetel. A küzdősportokban biztosítja az éberséget és a reakciósebességet anélkül, hogy a túlzott arousal által okozott alagútlátás kialakulna.",
          "A fő feladatod most ennek az állapotnak a fenntartása, ahelyett, hogy feleslegesen felpörgetnéd vagy lecsillapítanád magad. Maradj bekapcsolódva a bemelegítési rutinodba, tartsd a mozgásaidat célirányosnak, és kerüld a túl hosszas ülést (ami csökkentheti az arousalt) vagy a túlzott ingernek való kitettséget (ami megugraszthatja). Bízz a testedben -- azt mondja, kész. Ez az állapot-leolvasás erre a pillanatra vonatkozik, és a következő néhány percben való jó kezelése számít a legtöbbet.",
        ],
        de: [
          "Dein Körper zeigt ein moderates Maß an körperlicher Aktivierung -- etwas erhöhte Herzfrequenz, vielleicht etwas Muskelspannung oder Magenwahrnehmung, aber nichts Überwältigendes. Das wird oft als Zone der Wettkampfbereitschaft beschrieben. Dein sympathisches Nervensystem hat sich genug eingeschaltet, um deine Sinne zu schärfen und deine Muskeln auf explosive Anstrengung vorzubereiten, ohne in die Art von Übererregung zu kippen, die zitternde Hände, Übelkeit oder starre Bewegungsmuster verursacht.",
          "Moderate somatische Erregung vor dem Wettkampf ist generell ein positives Zeichen. Die Forschung zeigt durchgehend, dass die meisten Athleten bei mittleren körperlichen Aktivierungsniveaus am besten abschneiden -- genug Adrenalin, um scharf zu sein, nicht so viel, dass die Feinmotorik nachlässt. Im Kraftsport unterstützt dieser Zustand die Kombination aus maximaler Kraftentwicklung und präziser technischer Ausführung, die zum Gewinnen nötig ist. Im Kampfsport bietet er die Wachsamkeit und Reaktionsgeschwindigkeit, die gebraucht wird, ohne den Tunnelblick, den übermäßige Erregung verursachen kann.",
          "Deine Hauptaufgabe jetzt ist es, diesen Zustand beizubehalten, anstatt unnötig hochzufahren oder herunterzukommen. Bleibe in deiner Aufwärmroutine engagiert, halte deine Bewegungen zielgerichtet und vermeide es, zu lange stillzusitzen (was die Erregung abfallen lassen kann) oder dich übermäßiger Stimulation auszusetzen (was sie in die Höhe treiben kann). Vertraue deinem Körper -- er sagt dir, dass er bereit ist. Diese Zustandsmessung ist spezifisch für diesen Moment, und sie in den nächsten Minuten gut zu managen, ist das, was am meisten zählt.",
        ],
      },
      high: {
        en: [
          "Your body is sending strong physical arousal signals right now -- elevated heart rate, muscle tension, sweating, perhaps stomach discomfort or trembling. This level of somatic activation can feel uncomfortable, and if left unmanaged it can impair performance by reducing fine motor control, causing premature fatigue, and narrowing your perceptual field. However, high somatic arousal is not inherently bad -- it means your body is mobilised and ready to produce force. The challenge is to channel it rather than be overwhelmed by it.",
          "The most effective immediate strategy is controlled breathing. Slow, diaphragmatic exhales activate your parasympathetic nervous system and directly reduce heart rate and muscle tension. A simple protocol: inhale for 4 counts, hold for 2, exhale for 6. Repeat five to ten times. This is not about becoming calm -- it is about bringing your arousal from a 9 down to a 7, from counterproductive to competitive. Pair the breathing with progressive muscle relaxation if time allows: systematically tense and release major muscle groups to discharge excess tension.",
          "Be careful not to interpret these physical sensations as evidence that something is wrong. Many athletes misread arousal as anxiety and create a secondary cognitive spiral -- \"my heart is pounding, therefore I must be scared, therefore I will perform badly.\" The physical sensations are your body preparing for maximal effort. Relabel them: this is not fear, this is fuel. Elite performers consistently report high somatic arousal before their best performances. What matters is not the arousal itself but your relationship to it. This is a momentary reading -- manage the next ten minutes well and you can compete at your best.",
        ],
        hu: [
          "A tested most erős fizikai arousal-jeleket küld -- emelkedett szívfrekvencia, izomfeszültség, izzadás, talán gyomorkellemtlenség vagy remegés. A szomatikus aktiváció ilyen szintje kellemetlen lehet, és ha kezeletlen marad, ronthatja a teljesítményt azáltal, hogy csökkenti a finommotorikus kontrollt, korai fáradtságot okoz és szűkíti az észlelési meződet. Ugyanakkor a magas szomatikus arousal önmagában nem rossz -- azt jelenti, hogy a tested mobilizált és kész erőt termelni. A kihívás az, hogy kanalizáld ahelyett, hogy elárasztana.",
          "A leghatékonyabb azonnali stratégia a kontrollált légzés. A lassú, rekeszizmos kilégzések aktiválják a paraszimpatikus idegrendszeredet, és közvetlenül csökkentik a szívfrekvenciát és az izomfeszültséget. Egy egyszerű protokoll: lélegezz be 4 ütemre, tartsd 2 ütemig, lélegezz ki 6 ütemre. Ismételd ötször-tízszer. Ez nem arról szól, hogy nyugodttá válj -- arról, hogy az arousalodat 9-ről 7-re vidd, a kontraproduktívból a versenyképesbe. Ha az idő engedi, párosítsd a légzést progresszív izomlazítással: rendszeresen feszítsd meg és engedd el a fő izomcsoportokat a felesleges feszültség levezetésére.",
          "Vigyázz, ne értelmezd ezeket a fizikai érzéseket úgy, mint bizonyítékot arra, hogy valami baj van. Sok sportoló félreolvassa az arousalt szorongásként, és másodlagos kognitív spirált hoz létre -- \"kalapál a szívem, tehát biztosan félek, tehát rosszul fogok teljesíteni.\" A fizikai érzések a tested felkészülését jelentik a maximális erőfeszítésre. Címkézd át őket: ez nem félelem, ez üzemanyag. Az élitsportolók következetesen magas szomatikus arousalt jelentenek a legjobb teljesítményeik előtt. Nem maga az arousal számít, hanem a hozzáállásod. Ez egy pillanatnyi leolvasás -- kezeld jól a következő tíz percet, és a lehető legjobban versenyezhetsz.",
        ],
        de: [
          "Dein Körper sendet gerade starke körperliche Erregungssignale -- erhöhte Herzfrequenz, Muskelspannung, Schwitzen, vielleicht Magenbeschwerden oder Zittern. Dieses Niveau somatischer Aktivierung kann sich unangenehm anfühlen, und wenn es nicht gemanagt wird, kann es die Leistung beeinträchtigen, indem es die Feinmotorik reduziert, vorzeitige Ermüdung verursacht und dein Wahrnehmungsfeld verengt. Allerdings ist hohe somatische Erregung nicht grundsätzlich schlecht -- sie bedeutet, dass dein Körper mobilisiert und bereit ist, Kraft zu produzieren. Die Herausforderung ist, sie zu kanalisieren, anstatt von ihr überwältigt zu werden.",
          "Die effektivste Sofortstrategie ist kontrolliertes Atmen. Langsame, zwerchfellbetonte Ausatmungen aktivieren dein parasympathisches Nervensystem und reduzieren direkt Herzfrequenz und Muskelspannung. Ein einfaches Protokoll: 4 Zähler einatmen, 2 halten, 6 Zähler ausatmen. Fünf- bis zehnmal wiederholen. Es geht nicht darum, ruhig zu werden -- es geht darum, deine Erregung von einer 9 auf eine 7 zu bringen, von kontraproduktiv zu wettkampffähig. Kombiniere die Atmung mit progressiver Muskelentspannung, wenn die Zeit es erlaubt: spanne systematisch große Muskelgruppen an und löse sie, um überschüssige Spannung abzubauen.",
          "Achte darauf, diese körperlichen Empfindungen nicht als Beweis dafür zu interpretieren, dass etwas nicht stimmt. Viele Athleten lesen Erregung fälschlicherweise als Angst und erzeugen eine sekundäre kognitive Spirale -- \"mein Herz hämmert, also muss ich Angst haben, also werde ich schlecht abschneiden.\" Die körperlichen Empfindungen sind dein Körper, der sich auf maximale Anstrengung vorbereitet. Etikettiere sie um: das ist keine Angst, das ist Treibstoff. Spitzenathleten berichten durchgehend von hoher somatischer Erregung vor ihren besten Leistungen. Nicht die Erregung selbst zählt, sondern deine Beziehung zu ihr. Das ist eine momentane Messung -- manage die nächsten zehn Minuten gut und du kannst dein Bestes geben.",
        ],
      },
    },
  },

  // =========================================================================
  // SELF-CONFIDENCE
  // =========================================================================
  confidence: {
    name: {
      en: "Self-Confidence",
      hu: "Önbizalom",
      de: "Selbstvertrauen",
    },
    definition: {
      en: "Your belief in your ability to perform well and achieve your goals in this specific competition. This is a state judgement -- how confident you feel right now -- not a fixed personality trait. It reflects the intersection of your preparation, your recent form, and the meaning you assign to the upcoming event.",
      hu: "A meggyőződésed, hogy képes vagy jól teljesíteni és elérni a céljaidat ezen a konkrét versenyen. Ez egy állapot-ítélet -- mennyire érzed magad magabiztosnak most --, nem egy rögzült személyiségvonás. A felkészülésed, a közelmúltbeli formád és az elkövetkezendő eseményhez rendelt jelentés metszéspontját tükrözi.",
      de: "Dein Glaube an deine Fähigkeit, in diesem spezifischen Wettkampf gut abzuschneiden und deine Ziele zu erreichen. Das ist ein Zustandsurteil -- wie selbstsicher du dich gerade fühlst -- keine feste Persönlichkeitseigenschaft. Es spiegelt den Schnittpunkt deiner Vorbereitung, deiner jüngsten Form und der Bedeutung wider, die du dem bevorstehenden Event beimisst.",
    },
    bands: {
      low: {
        en: [
          "Your confidence going into this competition is low. You may be questioning whether your preparation was adequate, whether you belong at this level, or whether you can execute when it counts. This is uncomfortable but it is also honest data -- and honest data is always more useful than false bravado. The question now is not how to manufacture confidence you do not feel, but how to perform effectively despite its current absence.",
          "Low state confidence often has identifiable roots. Perhaps your recent training has not gone well. Perhaps you are facing an opponent you have lost to before, or the stakes feel unusually high. Identifying the specific source matters because it determines the response. If the root is preparation-related, remind yourself of the sessions that did go well -- you trained for this even if the last week was rough. If the root is opponent-related, shift your focus from outcome (winning or losing) to process (executing your techniques, following your game plan). You cannot control the opponent; you can control your execution.",
          "Confidence is not a prerequisite for performance. Many athletes have produced career-best results on days when they felt least confident, precisely because low confidence forced them to focus harder, prepare more meticulously, and leave nothing to chance. Use this state as fuel for discipline rather than evidence of inevitable failure. Take the next small step: complete your warm-up with intention, review your opening strategy, and commit to competing one exchange at a time. Confidence often returns once you start performing. This reading is a snapshot, not a sentence.",
        ],
        hu: [
          "Az önbizalmad alacsony erre a versenyre készülve. Lehet, hogy megkérdőjelezed, elég volt-e a felkészülés, odatartozol-e erre a szintre, vagy képes leszel-e teljesíteni, amikor számít. Ez kellemetlen, de becsületes adat is -- és a becsületes adat mindig hasznosabb, mint a hamis bravúr. A kérdés most nem az, hogyan gyárts olyan önbizalmat, amit nem érzel, hanem hogyan teljesíts hatékonyan annak jelenlegi hiánya ellenére.",
          "Az alacsony állapot-önbizalomnak gyakran azonosítható gyökerei vannak. Talán a közelmúltbeli edzéseid nem mentek jól. Talán olyan ellenfél áll előtted, akitől már kikapál, vagy a tét szokatlanul magasnak érződik. A konkrét forrás azonosítása azért számít, mert meghatározza a választ. Ha a gyökér a felkészüléssel kapcsolatos, emlékeztesd magad azokra az edzésekre, amelyek jól mentek -- készültél erre, még ha az utolsó hét nehéz is volt. Ha a gyökér az ellenféllel kapcsolatos, told el a fókuszodat az eredménytől (nyerés vagy vesztés) a folyamat felé (a technikáid végrehajtása, a versenyterved követése). Az ellenfelet nem tudod irányítani; a saját végrehajtásodat igen.",
          "Az önbizalom nem előfeltétele a teljesítménynek. Sok sportoló hozta a karrierje legjobb eredményeit olyan napokon, amikor a legkevésbé volt magabiztos, éppen azért, mert az alacsony önbizalom arra kényszerítette, hogy jobban fókuszáljon, gondosabban készüljön, és semmit ne bízzon a véletlenre. Használd ezt az állapotot a fegyelem üzemanyagaként, ne az elkerülhetetlen kudarc bizonyítékaként. Tedd meg a következő kis lépést: fejezd be a bemelegítésedet szándékkal, tekintsd át a nyitó stratégiádat, és kötelezd el magad amellett, hogy egyszerre egy cserét versenyzel. Az önbizalom gyakran visszatér, amint elkezdesz teljesíteni. Ez a leolvasás egy pillanatkép, nem egy ítélet.",
        ],
        de: [
          "Dein Selbstvertrauen vor diesem Wettkampf ist niedrig. Vielleicht fragst du dich, ob deine Vorbereitung ausreichend war, ob du auf dieses Niveau gehörst, oder ob du liefern kannst, wenn es zählt. Das ist unangenehm, aber es sind auch ehrliche Daten -- und ehrliche Daten sind immer nützlicher als falscher Übermut. Die Frage jetzt ist nicht, wie du Selbstvertrauen erzeugst, das du nicht fühlst, sondern wie du trotz seiner momentanen Abwesenheit effektiv abschneidest.",
          "Niedriges Zustandsvertrauen hat oft identifizierbare Wurzeln. Vielleicht lief dein Training in letzter Zeit nicht gut. Vielleicht stehst du einem Gegner gegenüber, gegen den du schon verloren hast, oder der Einsatz fühlt sich ungewöhnlich hoch an. Die spezifische Quelle zu identifizieren ist wichtig, weil sie die Reaktion bestimmt. Wenn die Wurzel mit der Vorbereitung zusammenhängt, erinnere dich an die Einheiten, die gut liefen -- du hast dafür trainiert, auch wenn die letzte Woche schwierig war. Wenn die Wurzel mit dem Gegner zusammenhängt, verschiebe deinen Fokus vom Ergebnis (gewinnen oder verlieren) zum Prozess (deine Techniken ausführen, deinem Wettkampfplan folgen). Du kannst den Gegner nicht kontrollieren; du kannst deine Ausführung kontrollieren.",
          "Selbstvertrauen ist keine Voraussetzung für Leistung. Viele Athleten haben ihre Karriere-Bestleistungen an Tagen erzielt, an denen sie sich am wenigsten selbstsicher fühlten, gerade weil niedriges Selbstvertrauen sie zwang, härter zu fokussieren, sorgfältiger vorzubereiten und nichts dem Zufall zu überlassen. Nutze diesen Zustand als Treibstoff für Disziplin, nicht als Beweis für unvermeidliches Scheitern. Mache den nächsten kleinen Schritt: beende dein Aufwärmen mit Absicht, gehe deine Eröffnungsstrategie durch und verpflichte dich, einen Austausch nach dem anderen zu bestreiten. Selbstvertrauen kehrt oft zurück, sobald du anfängst abzuliefern. Dieses Ergebnis ist eine Momentaufnahme, kein Urteil.",
        ],
      },
      average: {
        en: [
          "You feel reasonably confident heading into this competition -- not bulletproof, but not shaky either. You believe you can compete, you have some trust in your preparation, and you feel capable of executing your game plan. At the same time, there may be areas of uncertainty -- a technique you are not fully sure about, an opponent quality you respect, or a nagging awareness that your form is not at its peak. This is a realistic and grounded state that many successful athletes operate from.",
          "Moderate confidence is functional. It keeps you alert and respectful of the challenge without undermining your willingness to commit fully to your efforts. Athletes with very high confidence sometimes under-prepare or take unnecessary risks; athletes with moderate confidence tend to be thorough and disciplined. The potential downside is that if adversity strikes early in the competition, moderate confidence can erode quickly because it lacks the deep reserves that high confidence provides.",
          "To strengthen your position from here, focus on what you can control in the next few minutes. Nail your warm-up, rehearse your opening sequence mentally, and remind yourself of specific training moments where you performed at the level you need today. Build evidence-based confidence by stacking small wins -- a good warm-up set, a clean practice repetition, a composed interaction with your coach. Each one adds a small deposit to the confidence account. This is a state reading taken before competition -- it can shift upward once you begin performing and confirm to yourself that you are ready.",
        ],
        hu: [
          "Elfogadhatóan magabiztosnak érzed magad erre a versenyre készülve -- nem sebezhetetlen, de nem is bizonytalan. Hiszel abban, hogy tudsz versenyezni, van némi bizalmad a felkészülésedben, és képesnek érzed magad a versenyterved végrehajtására. Ugyanakkor lehetnek bizonytalansági területek -- egy technika, amiben nem vagy teljesen biztos, egy ellenféli minőség, amit tisztelsz, vagy egy rágódó tudatosság, hogy a formád nem a csúcspontján van. Ez egy realisztikus és megalapozott állapot, ahonnan sok sikeres sportoló működik.",
          "A mérsékelt önbizalom funkcionális. Éberen és tisztelettel tart a kihívással szemben, anélkül, hogy aláásná a hajlandóságodat a teljes elköteleződéssel való próbálkozásra. A nagyon magas önbizalmú sportolók néha alulkészülnek vagy felesleges kockázatokat vállalnak; a mérsékelt önbizalmú sportolók általában alaposak és fegyelmezettek. A potenciális hátránya az, hogy ha a verseny elején nehézség éri, a mérsékelt önbizalom gyorsan erodálódhat, mert hiányoznak azok a mély tartalékok, amelyeket a magas önbizalom biztosít.",
          "A pozíciód erősítéséhez innen fókuszálj arra, amit a következő néhány percben irányítani tudsz. Csináld meg jól a bemelegítésed, gyakorold mentálisan a nyitó szekvenciádat, és emlékeztesd magad konkrét edzéspillanatokra, ahol azon a szinten teljesítettél, amelyre ma szükséged van. Építs bizonyítékokon alapuló önbizalmat kis győzelmek halmozásával -- egy jó bemelegítő sorozat, egy tiszta gyakorló ismétlés, egy higgadt interakció az edződdel. Mindegyik kis befizetést jelent az önbizalom-számlára. Ez egy verseny előtt vett állapot-leolvasás -- felfelé mozdulhat, amint elkezdesz teljesíteni és megerősíteni magadnak, hogy kész vagy.",
        ],
        de: [
          "Du fühlst dich angemessen selbstsicher vor diesem Wettkampf -- nicht kugelsicher, aber auch nicht wackelig. Du glaubst, dass du konkurrieren kannst, du hast etwas Vertrauen in deine Vorbereitung und du fühlst dich fähig, deinen Wettkampfplan auszuführen. Gleichzeitig mag es Bereiche der Unsicherheit geben -- eine Technik, bei der du dir nicht völlig sicher bist, eine Gegnereigenschaft, die du respektierst, oder ein nagendes Bewusstsein, dass deine Form nicht auf dem Höhepunkt ist. Das ist ein realistischer und fundierter Zustand, von dem aus viele erfolgreiche Athleten agieren.",
          "Moderates Selbstvertrauen ist funktional. Es hält dich wachsam und respektvoll gegenüber der Herausforderung, ohne deine Bereitschaft zu untergraben, dich voll und ganz einzusetzen. Athleten mit sehr hohem Selbstvertrauen bereiten sich manchmal zu wenig vor oder gehen unnötige Risiken ein; Athleten mit moderatem Selbstvertrauen tendieren dazu, gründlich und diszipliniert zu sein. Der potenzielle Nachteil ist, dass moderates Selbstvertrauen schnell erodieren kann, wenn früh im Wettkampf Widrigkeiten auftreten, weil die tiefen Reserven fehlen, die hohes Selbstvertrauen bietet.",
          "Um deine Position von hier aus zu stärken, fokussiere dich auf das, was du in den nächsten Minuten kontrollieren kannst. Mache dein Aufwärmen gut, gehe deine Eröffnungssequenz mental durch und erinnere dich an spezifische Trainingsmomente, in denen du auf dem Niveau abgeliefert hast, das du heute brauchst. Baue evidenzbasiertes Selbstvertrauen auf, indem du kleine Erfolge stapelst -- ein guter Aufwärmsatz, eine saubere Übungswiederholung, eine gefasste Interaktion mit deinem Trainer. Jeder einzelne ist eine kleine Einzahlung auf das Selbstvertrauenskonto. Das ist eine Zustandsmessung vor dem Wettkampf -- sie kann nach oben wandern, sobald du anfängst abzuliefern und dir selbst bestätigst, dass du bereit bist.",
        ],
      },
      high: {
        en: [
          "You are heading into this competition with strong self-belief. You feel ready, you trust your preparation, and you expect to perform well. This is a genuine competitive asset -- research consistently links high pre-competition confidence to superior performance outcomes. Your confidence likely frees up cognitive resources that anxious athletes spend on worry, allowing you to focus on execution, tactics, and reading the competitive situation as it unfolds.",
          "High confidence is most valuable when it is grounded in evidence -- real training data, demonstrated ability, and honest self-assessment rather than wishful thinking or bravado. If your confidence comes from knowing you have put in the work, it is resilient and will hold up when the competition gets hard. If it is based on avoiding hard truths or underestimating the challenge, it is fragile and may collapse at the first sign of adversity. Be honest with yourself about which category yours falls into.",
          "The next challenge for a highly confident athlete is maintaining that confidence under adversity. Even the most self-assured competitors face moments where things do not go to plan -- a bad opening exchange, a missed attempt, an opponent who comes out stronger than expected. Your task is to protect your confidence through these moments by keeping your internal narrative constructive: \"That did not go as planned, but I know what I am capable of and I will adjust.\" High confidence is a starting position, not a guarantee. Use it well in the minutes ahead. This is a state reading -- it reflects your readiness right now, and your job is to translate it into performance.",
        ],
        hu: [
          "Erős önbizalommal mész bele ebbe a versenybe. Késznek érzed magad, bízol a felkészülésedben, és arra számítasz, hogy jól fogsz teljesíteni. Ez valós versenyelőny -- a kutatások következetesen összefüggésbe hozzák a magas verseny előtti önbizalmat a jobb teljesítményeredményekkel. Az önbizalmad valószínűleg felszabadítja azokat a kognitív erőforrásokat, amelyeket a szorongó sportolók aggodalomra fordítanak, lehetővé téve, hogy a végrehajtásra, a taktikára és a versenyhelyzet olvasására fókuszálj, ahogy az kibontakozik.",
          "A magas önbizalom akkor a legértékesebb, ha bizonyítékokon alapul -- valós edzésadatokon, bizonyított képességen és becsületes önértékelésen, nem pedig vágyakozó gondolkodáson vagy bravúron. Ha az önbizalmad abból fakad, hogy tudod, elvégezted a munkát, akkor ellenálló és kitart, amikor a verseny nehézzé válik. Ha azon alapul, hogy kerülöd a kemény igazságokat vagy alulbecsülöd a kihívást, akkor törékeny és összeomlhat a nehézség első jelére. Légy becsületes magaddal abban, melyik kategóriába esik a tied.",
          "A következő kihívás egy magasan magabiztos sportoló számára az önbizalom fenntartása nehézség idején. Még a legmagabiztosabb versenyzők is szembenéznek olyan pillanatokkal, amikor a dolgok nem a terv szerint alakulnak -- rossz nyitó csere, elrontott kísérlet, vagy egy ellenfél, aki az elvártnál erősebben jön ki. A feladatod az, hogy megvédd az önbizalmadat ezeken a pillanatokon át azáltal, hogy a belső narratívádat konstruktívan tartod: \"Ez nem a terv szerint ment, de tudom, mire vagyok képes, és alkalmazkodom.\" A magas önbizalom kiindulópontot, nem garanciát jelent. Használd jól az elkövetkezendő percekben. Ez egy állapot-leolvasás -- a jelenlegi készenlétédet tükrözi, és a feladatod az, hogy teljesítménnyé fordítsd.",
        ],
        de: [
          "Du gehst mit starkem Selbstvertrauen in diesen Wettkampf. Du fühlst dich bereit, du vertraust deiner Vorbereitung und du erwartest, gut abzuschneiden. Das ist ein echtes Wettbewerbsgut -- die Forschung verknüpft durchgehend hohes Selbstvertrauen vor dem Wettkampf mit überlegenen Leistungsergebnissen. Dein Selbstvertrauen befreit wahrscheinlich kognitive Ressourcen, die ängstliche Athleten für Sorgen aufwenden, und ermöglicht es dir, dich auf Ausführung, Taktik und das Lesen der Wettkampfsituation zu konzentrieren, wie sie sich entfaltet.",
          "Hohes Selbstvertrauen ist am wertvollsten, wenn es auf Beweisen basiert -- echten Trainingsdaten, bewiesener Fähigkeit und ehrlicher Selbsteinschätzung statt Wunschdenken oder Übermut. Wenn dein Selbstvertrauen daher kommt, dass du weißt, dass du die Arbeit geleistet hast, ist es belastbar und wird standhalten, wenn der Wettkampf hart wird. Wenn es darauf basiert, harte Wahrheiten zu vermeiden oder die Herausforderung zu unterschätzen, ist es fragil und könnte beim ersten Anzeichen von Widerstand zusammenbrechen. Sei ehrlich mit dir selbst, in welche Kategorie deines fällt.",
          "Die nächste Herausforderung für einen hoch selbstsicheren Athleten ist es, dieses Selbstvertrauen unter Widrigkeiten aufrechtzuerhalten. Selbst die selbstsichersten Wettkämpfer erleben Momente, in denen Dinge nicht nach Plan laufen -- ein schlechter Eröffnungsaustausch, ein verfehlter Versuch, ein Gegner, der stärker als erwartet herauskommt. Deine Aufgabe ist es, dein Selbstvertrauen durch diese Momente zu schützen, indem du dein internes Narrativ konstruktiv hältst: \"Das lief nicht wie geplant, aber ich weiß, wozu ich fähig bin, und ich werde mich anpassen.\" Hohes Selbstvertrauen ist eine Ausgangsposition, keine Garantie. Nutze es gut in den kommenden Minuten. Das ist eine Zustandsmessung -- sie spiegelt deine Bereitschaft gerade jetzt wider, und deine Aufgabe ist es, sie in Leistung umzusetzen.",
        ],
      },
    },
  },
};
