-- ─────────────────────────────────────────────────────────────────────────────
-- PowerFlow — Chat messages, conversation summaries, and plan_tier migration
--
-- Creates:
--   chat_messages          — persists AI coaching chat turns per user
--   conversation_summaries — structured session summaries generated by /api/chat/summarize
--
-- Adds:
--   profiles.plan_tier     — "opener" | "second" | "pr" (default "opener")
--
-- Idempotent: safe to run multiple times.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── plan_tier on profiles ────────────────────────────────────────────────────

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS plan_tier TEXT NOT NULL DEFAULT 'opener'
  CHECK (plan_tier IN ('opener', 'second', 'pr'));

-- ── chat_messages ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS chat_messages (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role        TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
  content     TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS chat_messages_user_id_created_at
  ON chat_messages (user_id, created_at DESC);

-- Row-Level Security: users can only read/write their own messages.
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "chat_messages_self" ON chat_messages;
CREATE POLICY "chat_messages_self"
  ON chat_messages
  FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Service role (used by admin API) bypasses RLS automatically.

-- ── conversation_summaries ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS conversation_summaries (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_date    DATE        NOT NULL DEFAULT CURRENT_DATE,
  summary         TEXT        NOT NULL,
  techniques_used TEXT[]      NOT NULL DEFAULT '{}',
  themes          TEXT[]      NOT NULL DEFAULT '{}',
  resonated       TEXT,
  message_count   INTEGER     NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS conversation_summaries_user_id_session_date
  ON conversation_summaries (user_id, session_date DESC);

ALTER TABLE conversation_summaries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "conversation_summaries_self" ON conversation_summaries;
CREATE POLICY "conversation_summaries_self"
  ON conversation_summaries
  FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ── PostgREST schema reload ──────────────────────────────────────────────────

NOTIFY pgrst, 'reload schema';
